import io
import logging
import os
from pathlib import Path
import re
import sys
from contextlib import redirect_stdout
from datetime import datetime, timezone
from types import ModuleType, SimpleNamespace
import unittest
from unittest.mock import Mock, patch
from uuid import uuid4

import psycopg2
from psycopg2 import extensions, sql


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


# Database tests do not fetch profiles, scrape tweets, or load local credentials
external_modules = {
    name: ModuleType(name)
    for name in ('yfinance', 'schedule', 'dotenv', 'twikit',
                 'monitors.health_monitor', 'nice_funcs.twitter_funcs')
}
external_modules['dotenv'].load_dotenv = lambda **kwargs: None
external_modules['yfinance'].Ticker = Mock(side_effect=AssertionError('Unexpected Yahoo request'))
external_modules['twikit'].TooManyRequests = type('TooManyRequests', (Exception,), {})
external_modules['monitors.health_monitor'].HealthMonitor = Mock()
twitter_helpers = external_modules['nice_funcs.twitter_funcs']
for name in ('setup_httpx_patching', 'init_vader_with_crypto_lexicon', 'get_pooled_client',
             'auto_refresh_cookies', 'get_db_connection', 'calculate_whale_velocity_metrics',
             'update_whale_sentiment_history'):
    setattr(twitter_helpers, name, Mock())
twitter_helpers.analyze_sentiment = Mock(return_value=0.5)
twitter_helpers.calculate_bot_probability = Mock(return_value=0.0)
twitter_helpers.calculate_influence_weight = Mock(return_value=0.5)
twitter_helpers.validate_sentiment_data = lambda **kwargs: kwargs
with patch.dict(sys.modules, external_modules):
    from fundamentals_data import yfinance_fundamentals_reader as profiles
    from crypto_scrapers import twitter_whales


class RecordingConnection(extensions.connection):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.opened_cursors = []

    def cursor(self, *args, **kwargs):
        cursor = super().cursor(*args, **kwargs)
        self.opened_cursors.append(cursor)
        return cursor


def profile(number):
    return {
        'symbol': f'TEST{number}', 'longName': f'Company {number}',
        'exchange': 'NASDAQ', 'industry': 'Software', 'sector': 'Technology',
        'marketCap': 1000000, 'beta': 1.0, 'trailingPE': 20.0,
        'trailingEps': 2.0, 'website': 'https://example.com',
    }


def tweet(number, tokens=None):
    return {
        'tweet_id': str(number), 'username': 'blknoiz06', 'text': 'Watching BTC',
        'followers': 10000, 'following': 100, 'retweets': 1, 'likes': 2,
        'replies': 0, 'quotes': 0,
        'created_at': datetime(2026, 1, 1, tzinfo=timezone.utc),
        'timestamp': datetime(2026, 1, 1, tzinfo=timezone.utc),
        'mentioned_tokens': ['BTC'] if tokens is None else tokens,
    }


class ProfileWhaleSaveTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.database_url = os.environ.get('TEST_DATABASE_URL')
        if not cls.database_url:
            raise RuntimeError('Set TEST_DATABASE_URL to a disposable PostgreSQL database.')

    def setUp(self):
        self.schema_name = 'test_profile_whale_saves_' + uuid4().hex
        self.addCleanup(self.drop_schema)
        schema = (ROOT / 'data/pjx_database_schema.sql').read_text(encoding='utf-8')
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(self.schema_name)))
                cursor.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(
                    sql.Identifier(self.schema_name)
                ))
                for table in ('company_profiles', 'twitter_sentiment'):
                    match = re.search(r'CREATE TABLE public\.' + table + r' \((.*?)\n\);', schema, re.DOTALL)
                    self.assertIsNotNone(match)
                    cursor.execute(sql.SQL('CREATE TABLE {} ({})').format(
                        sql.Identifier(table), sql.SQL(match.group(1))
                    ))
                    cursor.execute(sql.SQL(
                        'ALTER TABLE {} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
                    ).format(sql.Identifier(table)))
                    cursor.execute(sql.SQL('ALTER TABLE {} ADD PRIMARY KEY (id)').format(sql.Identifier(table)))
                cursor.execute('ALTER TABLE company_profiles ADD UNIQUE (symbol)')
                cursor.execute('ALTER TABLE twitter_sentiment ADD UNIQUE (tweet_id, token)')
            conn.commit()
        finally:
            conn.close()

    def connect(self):
        conn = psycopg2.connect(
            self.database_url, connect_timeout=10, connection_factory=RecordingConnection
        )
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(
                    sql.Identifier(self.schema_name)
                ))
            conn.commit()
        except Exception:
            conn.close()
            raise
        return conn

    def query(self, statement):
        conn = self.connect()
        try:
            with conn.cursor() as cursor:
                cursor.execute(statement)
                rows = cursor.fetchall() if cursor.description else None
            conn.commit()
            return rows
        finally:
            conn.close()

    def drop_schema(self):
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('DROP SCHEMA IF EXISTS {} CASCADE').format(
                    sql.Identifier(self.schema_name)
                ))
            conn.commit()
        finally:
            conn.close()

    def reject_commit(self, table):
        self.query('''
            CREATE OR REPLACE FUNCTION reject_profile_whale_commit() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'test commit failure';
            END;
            $$;
        ''')
        self.query(sql.SQL('''
            CREATE CONSTRAINT TRIGGER reject_profile_whale_commit
            AFTER INSERT OR UPDATE ON {} DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION reject_profile_whale_commit()
        ''').format(sql.Identifier(table)))

    def store_profiles(self, records):
        by_symbol = {item['symbol']: item for item in records}

        def ticker(symbol):
            item = by_symbol[symbol]
            if item.get('fetch_error'):
                raise RuntimeError('test Yahoo fetch failure')
            return SimpleNamespace(info={} if item.get('empty') else item)

        conn = self.connect()
        self.addCleanup(conn.close)
        with patch.object(profiles, 'get_db_connection', return_value=conn), \
                patch.object(profiles, 'TICKERS_TO_MONITOR', list(by_symbol)), \
                patch.object(profiles.yf, 'Ticker', side_effect=ticker) as fetch, \
                patch.object(profiles.time, 'sleep'), \
                patch.object(logging, 'info') as info, patch.object(logging, 'error') as error:
            result = profiles.fetch_and_store_fundamentals()
        self.assertIsNone(result)
        self.assertTrue(conn.closed)
        self.assertEqual([call.args[0] for call in fetch.call_args_list], list(by_symbol))
        return SimpleNamespace(
            messages=[call.args[0] for call in info.call_args_list],
            errors=[call.args[0] for call in error.call_args_list],
        )

    def store_whales(self, records, conn=None):
        if conn is None:
            conn = self.connect()
            self.addCleanup(conn.close)
        tracker = twitter_whales.WhaleTracker.__new__(twitter_whales.WhaleTracker)
        tracker.vader = None
        tracker.db_pool = SimpleNamespace(
            get_connection=Mock(return_value=conn), return_connection=Mock()
        )
        output = io.StringIO()
        with redirect_stdout(output):
            result = tracker.save_to_db(records)
        if records:
            tracker.db_pool.return_connection.assert_called_once_with(conn)
            self.assertFalse(conn.closed)
            self.assertEqual(conn.get_transaction_status(), extensions.TRANSACTION_STATUS_IDLE)
            self.assertTrue(all(cursor.closed for cursor in conn.opened_cursors))
        else:
            tracker.db_pool.get_connection.assert_not_called()
            tracker.db_pool.return_connection.assert_not_called()
        return result, output.getvalue()

    def stored_symbols(self):
        return [row[0] for row in self.query('SELECT symbol FROM company_profiles ORDER BY symbol')]

    def stored_tweets(self):
        return self.query('SELECT tweet_id, token FROM twitter_sentiment ORDER BY tweet_id, token')

    def assert_profile_count(self, count, report):
        self.assertIn(f'Fundamentals fetch complete. Upserted data for {count} companies.', report.messages)

    def test_profile_rejection_does_not_discard_other_upserts(self):
        for bad_index in (0, 2, 4):
            with self.subTest(bad_index=bad_index):
                self.query('TRUNCATE company_profiles')
                records = [profile(i) for i in range(1, 6)]
                records[bad_index]['longName'] = 'x' * 256
                report = self.store_profiles(records)
                expected = [item['symbol'] for i, item in enumerate(records) if i != bad_index]
                self.assertEqual(self.stored_symbols(), expected)
                self.assert_profile_count(4, report)
                self.assertEqual(len(report.errors), 1)
                self.assertIn('Database upsert failed', report.errors[0])
                self.assertIn('value too long', report.errors[0])

    def test_profile_update_survives_later_rejection(self):
        self.store_profiles([profile(1)])
        records = [profile(1), profile(2), profile(3)]
        records[0]['longName'] = 'Updated company'
        records[1]['longName'] = 'x' * 256
        report = self.store_profiles(records)
        self.assertEqual(self.query('SELECT symbol, company_name FROM company_profiles ORDER BY symbol'),
                         [('TEST1', 'Updated company'), ('TEST3', 'Company 3')])
        self.assert_profile_count(2, report)

    def test_profile_fetch_failure_or_empty_data_does_not_poison_batch(self):
        for field in ('fetch_error', 'empty'):
            with self.subTest(field=field):
                self.query('TRUNCATE company_profiles')
                records = [profile(1), profile(2), profile(3)]
                records[1][field] = True
                report = self.store_profiles(records)
                self.assertEqual(self.stored_symbols(), ['TEST1', 'TEST3'])
                self.assert_profile_count(2, report)
                if field == 'fetch_error':
                    self.assertEqual(len(report.errors), 1)
                    self.assertIn('Failed to fetch or read data for TEST2.', report.errors[0])
                else:
                    self.assertEqual(report.errors, [])

    def test_profile_commit_failure_does_not_report_upserts(self):
        self.store_profiles([profile(1)])
        self.reject_commit('company_profiles')
        records = [profile(1), profile(2)]
        records[0]['longName'] = 'Not committed'
        report = self.store_profiles(records)
        self.assertEqual(self.query('SELECT symbol, company_name FROM company_profiles'), [('TEST1', 'Company 1')])
        self.assertFalse(any('fetch complete.' in message or 'Successfully upserted' in message
                             for message in report.messages))
        self.assertTrue(any('test commit failure' in message for message in report.errors))

    def test_profile_repeated_run_counts_updates(self):
        records = [profile(1), profile(2)]
        self.store_profiles(records)
        report = self.store_profiles(records)
        self.assertEqual(self.stored_symbols(), ['TEST1', 'TEST2'])
        self.assert_profile_count(2, report)

    def test_empty_profile_run_reports_zero(self):
        report = self.store_profiles([])
        self.assertEqual(self.stored_symbols(), [])
        self.assert_profile_count(0, report)

    def test_whale_rejection_does_not_discard_other_records(self):
        for bad_index in (0, 2, 4):
            with self.subTest(bad_index=bad_index):
                self.query('TRUNCATE twitter_sentiment')
                records = [tweet(i) for i in range(1, 6)]
                records[bad_index]['mentioned_tokens'] = ['x' * 21]
                result, output = self.store_whales(records)
                expected = [(item['tweet_id'], 'BTC') for i, item in enumerate(records) if i != bad_index]
                self.assertEqual(self.stored_tweets(), expected)
                self.assertEqual(result, 4)
                self.assertIn('Saved 4 new whale tweet/token records', output)
                self.assertIn('4 high-signal tweets detected (saved to database)', output)
                self.assertEqual(output.count('[WARNING] Failed to insert whale tweet'), 1)
                self.assertNotIn('current transaction is aborted', output)

    def test_whale_tokens_are_saved_independently(self):
        result, output = self.store_whales([tweet(1, ['BTC', 'x' * 21, 'ETH'])])
        self.assertEqual(self.stored_tweets(), [('1', 'BTC'), ('1', 'ETH')])
        self.assertEqual(result, 2)
        self.assertIn('Saved 2 new whale tweet/token records', output)
        self.assertIn('1 high-signal tweets detected (saved to database)', output)

    def test_whale_duplicates_and_rejections_do_not_inflate_summary(self):
        self.store_whales([tweet(1)])
        result, output = self.store_whales([tweet(1), tweet(2, ['x' * 21]), tweet(3)])
        self.assertEqual(self.stored_tweets(), [('1', 'BTC'), ('3', 'BTC')])
        self.assertEqual(result, 1)
        self.assertIn('1 high-signal tweets detected (saved to database)', output)
        result, output = self.store_whales([tweet(1), tweet(3)])
        self.assertEqual(result, 0)
        self.assertNotIn('high-signal tweets detected', output)

    def test_whale_signal_summary_counts_each_saved_tweet_once(self):
        result, output = self.store_whales([tweet(1, ['BTC']), tweet(1, ['ETH'])])
        self.assertEqual(result, 2)
        self.assertEqual(self.stored_tweets(), [('1', 'BTC'), ('1', 'ETH')])
        self.assertIn('1 high-signal tweets detected (saved to database)', output)

    def test_whale_commit_failure_returns_zero_and_connection_can_be_reused(self):
        conn = self.connect()
        self.addCleanup(conn.close)
        self.reject_commit('twitter_sentiment')
        records = [tweet(1), tweet(2)]
        result, output = self.store_whales(records, conn)
        self.assertEqual(result, 0)
        self.assertEqual(self.stored_tweets(), [])
        self.assertIn('test commit failure', output)
        self.assertNotIn('[OK] Saved', output)
        self.assertNotIn('high-signal tweets detected', output)
        self.query('DROP TRIGGER reject_profile_whale_commit ON twitter_sentiment')
        result, _ = self.store_whales(records, conn)
        self.assertEqual(result, 2)
        self.assertEqual(self.stored_tweets(), [('1', 'BTC'), ('2', 'BTC')])

    def test_whale_empty_and_missing_connection_return_zero(self):
        result, _ = self.store_whales([])
        self.assertEqual(result, 0)
        tracker = twitter_whales.WhaleTracker.__new__(twitter_whales.WhaleTracker)
        tracker.db_pool = SimpleNamespace(
            get_connection=Mock(return_value=None), return_connection=Mock()
        )
        with redirect_stdout(io.StringIO()):
            self.assertEqual(tracker.save_to_db([tweet(1)]), 0)
        tracker.db_pool.return_connection.assert_not_called()

    def test_whale_rejected_batch_reports_zero(self):
        result, output = self.store_whales([tweet(1, ['x' * 21]), tweet(2, ['x' * 21])])
        self.assertEqual(result, 0)
        self.assertEqual(self.stored_tweets(), [])
        self.assertIn('Saved 0 new whale tweet/token records', output)
        self.assertNotIn('high-signal tweets detected', output)
        self.assertEqual(output.count('value too long'), 2)

    def test_whale_without_tokens_uses_general(self):
        result, output = self.store_whales([tweet(1, [])])
        self.assertEqual(result, 1)
        self.assertEqual(self.stored_tweets(), [('1', 'GENERAL')])
        self.assertNotIn('high-signal tweets detected', output)


if __name__ == '__main__':
    unittest.main()
