import logging
import os
from pathlib import Path
import re
import sys
from datetime import datetime, timezone
from types import ModuleType, SimpleNamespace
import unittest
from unittest.mock import Mock, patch
from uuid import uuid4

import psycopg2
from psycopg2 import sql


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


class RequestError(Exception):
    pass


# Keep API calls, local credentials, and heartbeat files out of database tests
external_modules = {
    name: ModuleType(name)
    for name in ('feedparser', 'schedule', 'dotenv', 'requests', 'fredapi', 'scraper_utils.heartbeat')
}
external_modules['dotenv'].load_dotenv = lambda: None
external_modules['fredapi'].Fred = Mock(side_effect=AssertionError('Unexpected FRED client'))
external_modules['feedparser'].parse = Mock(side_effect=AssertionError('Unexpected feed parsing'))
external_modules['requests'].get = Mock(side_effect=AssertionError('Unexpected API request'))
external_modules['requests'].exceptions = SimpleNamespace(RequestException=RequestError)
external_modules['scraper_utils.heartbeat'].touch_heartbeat = Mock()
with patch.dict(sys.modules, external_modules), patch.dict(os.environ, {
    'FRED_API_KEY': 'test-key', 'SEC_FORM_TYPES': '8-K', 'SEC_POLL_INTERVAL_MINUTES': '5',
}):
    from fundamentals_data import fred_data_reader, edgar_rss_reader


WRITERS = (fred_data_reader, edgar_rss_reader)
TABLES = {
    fred_data_reader: 'economic_indicators',
    edgar_rss_reader: 'sec_filings',
}


def record(number):
    return {
        'code': f'TEST{number}',
        'value': float(number),
        'company_name': f'Company {number}',
        'cik': f'{number:010d}',
        'filing_url': f'https://example.com/filing/{number}',
        'form_type': '8-K',
    }


def reject_record(item):
    item['code'] += 'x' * 21
    item['company_name'] = 'x' * 256


class FundamentalsSaveTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.database_url = os.environ.get('TEST_DATABASE_URL')
        if not cls.database_url:
            raise RuntimeError('Set TEST_DATABASE_URL to a disposable PostgreSQL database.')

    def setUp(self):
        self.schema_name = 'test_fundamentals_saves_' + uuid4().hex
        self.app_connections = []
        self.addCleanup(self.drop_schema)
        schema = (ROOT / 'data/pjx_database_schema.sql').read_text(encoding='utf-8')
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(self.schema_name)))
                cursor.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(
                    sql.Identifier(self.schema_name)
                ))
                for table in TABLES.values():
                    match = re.search(r'CREATE TABLE public\.' + table + r' \((.*?)\n\);', schema, re.DOTALL)
                    self.assertIsNotNone(match)
                    cursor.execute(sql.SQL('CREATE TABLE {} ({})').format(
                        sql.Identifier(table), sql.SQL(match.group(1))
                    ))
                    cursor.execute(sql.SQL(
                        'ALTER TABLE {} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
                    ).format(sql.Identifier(table)))
                    cursor.execute(sql.SQL('ALTER TABLE {} ADD PRIMARY KEY (id)').format(sql.Identifier(table)))
                cursor.execute('ALTER TABLE economic_indicators ADD UNIQUE (indicator_code, date)')
                cursor.execute('ALTER TABLE sec_filings ADD UNIQUE (filing_url)')
            conn.commit()
        finally:
            conn.close()

    def connect(self):
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(
                    sql.Identifier(self.schema_name)
                ))
            conn.commit()
        except Exception:
            conn.close()
            raise
        return conn

    def app_connection(self):
        conn = self.connect()
        self.app_connections.append(conn)
        self.addCleanup(conn.close)
        return conn

    def query(self, statement):
        conn = self.connect()
        try:
            with conn.cursor() as cursor:
                cursor.execute(statement)
                rows = cursor.fetchall() if cursor.description else None
            conn.commit()
            return rows
        finally:
            conn.close()

    def drop_schema(self):
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('DROP SCHEMA IF EXISTS {} CASCADE').format(
                    sql.Identifier(self.schema_name)
                ))
            conn.commit()
        finally:
            conn.close()

    def store(self, writer, records):
        by_code = {item['code']: item for item in records}

        def latest_release(code):
            item = by_code[code]
            if item.get('fetch_error'):
                raise RuntimeError('test FRED fetch failure')
            return SimpleNamespace(
                empty=item.get('empty', False),
                index=[datetime(2026, 1, 1, tzinfo=timezone.utc)],
                iloc=[item['value']],
            )

        fred = Mock()
        fred.get_series_latest_release.side_effect = latest_release
        entries = []
        for item in reversed(records):
            fields = {
                'title': item.get('title', f"{item['form_type']} - {item['company_name']} ({item['cik']}) (Filer)"),
                'link': item['filing_url'],
                'tags': [{'term': item['form_type']}],
                'updated_parsed': datetime(2026, 1, 1, tzinfo=timezone.utc).timetuple(),
            }
            entries.append(SimpleNamespace(**fields, get=fields.get))
        response = Mock(content=b'test feed')
        feed = SimpleNamespace(bozo=False, entries=entries)

        with patch.object(writer, 'get_db_connection', side_effect=self.app_connection), \
                patch.object(fred_data_reader, 'Fred', return_value=fred), \
                patch.object(fred_data_reader, 'INDICATORS', {code: code for code in by_code}), \
                patch.object(edgar_rss_reader.requests, 'get', return_value=response), \
                patch.object(edgar_rss_reader.feedparser, 'parse', return_value=feed), \
                patch.object(edgar_rss_reader, 'FORM_TYPE_FILTER', ['8-K']), \
                patch.object(edgar_rss_reader, 'touch_heartbeat') as heartbeat, \
                patch.object(writer.time, 'sleep'), \
                patch.object(logging, 'info') as info, \
                patch.object(logging, 'error') as error, patch.object(logging, 'warning') as warning:
            if writer is fred_data_reader:
                result = writer.fetch_and_store_fred_data()
                self.assertEqual(
                    [call.args[0] for call in fred.get_series_latest_release.call_args_list], list(by_code)
                )
            else:
                result = writer.fetch_and_store_sec_filings()
        self.assertIsNone(result)
        self.assertTrue(all(conn.closed for conn in self.app_connections))
        return SimpleNamespace(
            messages=[call.args[0] for call in info.call_args_list],
            errors=[call.args[0] for call in error.call_args_list],
            warnings=[call.args[0] for call in warning.call_args_list],
            heartbeat=heartbeat,
        )

    def stored_keys(self, writer):
        # Read committed rows through a different connection
        if writer is fred_data_reader:
            rows = self.query('SELECT indicator_code FROM economic_indicators ORDER BY indicator_code')
        else:
            rows = self.query('SELECT filing_url FROM sec_filings ORDER BY filing_url')
        return [row[0] for row in rows]

    def expected_keys(self, writer, records):
        key = 'code' if writer is fred_data_reader else 'filing_url'
        return sorted({item[key] for item in records})

    def assert_reported(self, writer, count, report):
        if writer is fred_data_reader:
            message = f'FRED data fetch complete. Added {count} new data points.'
        else:
            message = f'SEC filing fetch complete. Added {count} new filings.'
            report.heartbeat.assert_called_once_with('SEC EDGAR Reader')
        self.assertIn(message, report.messages)

    def test_rejected_middle_record_keeps_earlier_and_later_records(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                records = [record(i) for i in range(1, 6)]
                reject_record(records[2])
                report = self.store(writer, records)
                good = records[:2] + records[3:]
                self.assertEqual(self.stored_keys(writer), self.expected_keys(writer, good))
                self.assert_reported(writer, 4, report)
                self.assertEqual(len(report.errors), 1)
                self.assertIn('Database insert failed', report.errors[0])
                self.assertIn('value too long', report.errors[0])

    def test_rejected_first_or_last_record_does_not_poison_batch(self):
        for writer in WRITERS:
            for bad_index in (0, 4):
                with self.subTest(writer=writer.__name__, bad_index=bad_index):
                    self.query('TRUNCATE economic_indicators, sec_filings')
                    records = [record(i) for i in range(1, 6)]
                    reject_record(records[bad_index])
                    report = self.store(writer, records)
                    good = [item for i, item in enumerate(records) if i != bad_index]
                    self.assertEqual(self.stored_keys(writer), self.expected_keys(writer, good))
                    self.assert_reported(writer, 4, report)
                    self.assertEqual(len(report.errors), 1)

    def test_duplicates_and_rejected_records_are_not_counted(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                self.store(writer, [record(1), record(4)])
                records = [record(i) for i in range(1, 6)]
                reject_record(records[2])
                report = self.store(writer, records)
                good = [record(i) for i in (1, 2, 4, 5)]
                self.assertEqual(self.stored_keys(writer), self.expected_keys(writer, good))
                self.assert_reported(writer, 2, report)

    def test_all_rejected_records_log_zero_without_cascading_errors(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                records = [record(i) for i in range(1, 4)]
                for item in records:
                    reject_record(item)
                report = self.store(writer, records)
                self.assertEqual(self.stored_keys(writer), [])
                self.assert_reported(writer, 0, report)
                self.assertEqual(len(report.errors), 3)
                self.assertTrue(all('value too long' in message for message in report.errors))

    def test_failed_commit_does_not_report_success(self):
        self.query('''
            CREATE FUNCTION reject_fundamentals_commit() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'test commit failure';
            END;
            $$;
            CREATE CONSTRAINT TRIGGER reject_fundamentals_commit
            AFTER INSERT ON economic_indicators DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION reject_fundamentals_commit();
            CREATE CONSTRAINT TRIGGER reject_fundamentals_commit
            AFTER INSERT ON sec_filings DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION reject_fundamentals_commit();
        ''')
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                report = self.store(writer, [record(1), record(2)])
                self.assertEqual(self.stored_keys(writer), [])
                self.assertFalse(any('fetch complete.' in message for message in report.messages))
                self.assertFalse(any('> New' in message for message in report.messages))
                self.assertTrue(any('test commit failure' in message for message in report.errors))
                report.heartbeat.assert_not_called()

    def test_empty_run_logs_zero(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                report = self.store(writer, [])
                self.assertEqual(self.stored_keys(writer), [])
                self.assert_reported(writer, 0, report)

    def test_repeated_run_does_not_count_existing_records(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                records = [record(1), record(2)]
                first = self.store(writer, records)
                second = self.store(writer, records)
                self.assertEqual(self.stored_keys(writer), self.expected_keys(writer, records))
                self.assert_reported(writer, 2, first)
                self.assert_reported(writer, 0, second)

    def test_values_at_column_limits_are_preserved(self):
        item = record(1)
        item['code'] = 'x' * 20
        item['company_name'] = 'x' * 255
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                report = self.store(writer, [item])
                self.assertEqual(self.stored_keys(writer), self.expected_keys(writer, [item]))
                self.assert_reported(writer, 1, report)
        self.assertEqual(self.query('SELECT company_name FROM sec_filings'), [(item['company_name'],)])

    def test_fred_unavailable_data_keeps_other_indicators(self):
        for field, value in [('fetch_error', True), ('empty', True), ('value', 'not a number')]:
            with self.subTest(field=field):
                self.query('TRUNCATE economic_indicators')
                records = [record(i) for i in range(1, 6)]
                records[2][field] = value
                report = self.store(fred_data_reader, records)
                good = records[:2] + records[3:]
                self.assertEqual(self.stored_keys(fred_data_reader), self.expected_keys(fred_data_reader, good))
                self.assert_reported(fred_data_reader, 4, report)
                if field == 'empty':
                    self.assertEqual(report.errors, [])
                    self.assertEqual(report.warnings, ['No data returned for TEST3.'])
                else:
                    self.assertEqual(len(report.errors), 1)
                    self.assertIn('Failed to fetch or read data for TEST3.', report.errors[0])

    def test_edgar_filters_and_unparseable_titles_are_skipped(self):
        records = [record(i) for i in range(1, 6)]
        records[1]['form_type'] = '10-K'
        records[2]['title'] = 'Unparseable title'
        report = self.store(edgar_rss_reader, records)
        good = [records[i] for i in (0, 3, 4)]
        self.assertEqual(self.stored_keys(edgar_rss_reader), self.expected_keys(edgar_rss_reader, good))
        self.assert_reported(edgar_rss_reader, 3, report)
        self.assertEqual(report.errors, [])
        self.assertEqual(report.warnings, ['Could not parse title: Unparseable title'])


if __name__ == '__main__':
    unittest.main()
