import io
import os
from pathlib import Path
import re
import sys
from contextlib import redirect_stdout
from datetime import datetime, timezone
from types import ModuleType
import unittest
from unittest.mock import patch

import psycopg2
from psycopg2 import sql
from psycopg2.extensions import TRANSACTION_STATUS_IDLE


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Keep API clients and local .env files out of database tests
external_modules = {name: ModuleType(name) for name in ('ccxt', 'requests', 'websocket', 'dotenv')}
external_modules['dotenv'].load_dotenv = lambda **kwargs: None
with patch.dict(sys.modules, external_modules):
    from crypto_scrapers.binance_ohlcv import BinanceOHLCVScraper
    from crypto_scrapers.binance_funding import FundingRateScraper
    from crypto_scrapers.binance_oi import OpenInterestScraper
    from crypto_scrapers.binance_orderbook import OrderBookScraper
    from crypto_scrapers.binance_liquidations import LiquidationScraper


SCRAPERS = (
    (BinanceOHLCVScraper, 'crypto_ohlcv'),
    (FundingRateScraper, 'funding_rates'),
    (OpenInterestScraper, 'open_interest'),
    (OrderBookScraper, 'order_book_depth'),
    (LiquidationScraper, 'liquidations'),
)


def record(token):
    timestamp = datetime(2026, 1, 1, tzinfo=timezone.utc)
    return {
        'token': token, 'timestamp': timestamp, 'source': 'binance',
        'timeframe': '5m', 'open': 100, 'high': 110, 'low': 90,
        'close': 105, 'volume': 10,
        'funding_rate': 0.0001, 'next_funding_time': timestamp,
        'mark_price': 100, 'index_price': 100,
        'open_interest_contracts': 10, 'open_interest_usd': 1000,
        'best_bid': 99, 'best_ask': 101, 'bid_ask_spread': 2,
        'bid_liquidity_1pct': 500, 'ask_liquidity_1pct': 400,
        'order_imbalance': 0.1, 'total_bid_volume': 5, 'total_ask_volume': 4,
        'side': 'SELL', 'liquidation_value': 100, 'price': 100, 'quantity': 1,
    }


class BinanceSaveTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.database_url = os.environ.get('TEST_DATABASE_URL')
        if not cls.database_url:
            raise RuntimeError('Set TEST_DATABASE_URL to a disposable PostgreSQL database.')

    def setUp(self):
        self.conn = psycopg2.connect(self.database_url, connect_timeout=10)
        self.addCleanup(self.conn.close)
        self.addCleanup(self.clear_session)

        # Copy the real column definitions into session-only tables
        schema = (ROOT / 'data/pjx_database_schema.sql').read_text(encoding='utf-8')
        with self.conn.cursor() as cursor:
            for _, table in SCRAPERS:
                match = re.search(
                    rf'CREATE TABLE public\.{table} \((.*?)\n\);', schema, re.DOTALL
                )
                self.assertIsNotNone(match, table)
                cursor.execute(sql.SQL('CREATE TEMP TABLE {} ({})').format(
                    sql.Identifier(table), sql.SQL(match.group(1))
                ))
                cursor.execute(sql.SQL(
                    'ALTER TABLE {} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
                ).format(sql.Identifier(table)))
                cursor.execute(sql.SQL('ALTER TABLE {} ADD PRIMARY KEY (id)').format(
                    sql.Identifier(table)
                ))
            cursor.execute('''
                ALTER TABLE crypto_ohlcv
                ADD UNIQUE (token, timeframe, timestamp, source)
            ''')
            cursor.execute('SET search_path TO pg_temp')
        self.conn.commit()

    def clear_session(self):
        self.conn.rollback()
        self.conn.autocommit = True
        with self.conn.cursor() as cursor:
            cursor.execute('DISCARD ALL')

    def scraper(self, cls):
        scraper = cls()
        scraper.db_conn = self.conn
        return scraper

    def save(self, scraper, records):
        output = io.StringIO()
        with redirect_stdout(output):
            if isinstance(scraper, LiquidationScraper):
                scraper.pending_liquidations = list(records)
                result = scraper.save_to_db()
            else:
                result = scraper.save_to_db(records)
        return result, output.getvalue()

    def assert_reported(self, scraper, expected, result, output):
        if isinstance(scraper, LiquidationScraper):
            if expected:
                self.assertIn(f'Saved {expected} liquidations', output)
            else:
                self.assertNotRegex(output, r'Saved \d+ liquidations')
        else:
            self.assertEqual(result, expected)

    def stored_tokens(self, table):
        # A rollback here exposes writes that were never committed
        self.conn.rollback()
        with self.conn.cursor() as cursor:
            cursor.execute(sql.SQL('SELECT token FROM {} ORDER BY token').format(
                sql.Identifier(table)
            ))
            return [row[0] for row in cursor.fetchall()]

    def clear_table(self, table):
        self.conn.rollback()
        with self.conn.cursor() as cursor:
            cursor.execute(sql.SQL('TRUNCATE {}').format(sql.Identifier(table)))
        self.conn.commit()

    def reject_at_commit(self, table):
        self.conn.rollback()
        with self.conn.cursor() as cursor:
            cursor.execute('''
                CREATE OR REPLACE FUNCTION pg_temp.reject_test_commit()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    RAISE EXCEPTION 'test commit failure';
                END;
                $$
            ''')
            cursor.execute(sql.SQL('''
                CREATE CONSTRAINT TRIGGER reject_test_commit
                AFTER INSERT OR UPDATE ON {}
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW EXECUTE FUNCTION pg_temp.reject_test_commit()
            ''').format(sql.Identifier(table)))
        self.conn.commit()

    def remove_commit_failure(self, table):
        with self.conn.cursor() as cursor:
            cursor.execute(sql.SQL('DROP TRIGGER reject_test_commit ON {}').format(
                sql.Identifier(table)
            ))
        self.conn.commit()

    def test_empty_batch_does_not_need_a_connection(self):
        for cls, _ in SCRAPERS:
            with self.subTest(scraper=cls.__name__):
                scraper = cls()
                result, output = self.save(scraper, [])
                self.assert_reported(scraper, 0, result, output)

    def test_valid_rows_are_committed_and_reported(self):
        for cls, table in SCRAPERS:
            with self.subTest(scraper=cls.__name__):
                scraper = self.scraper(cls)
                result, output = self.save(scraper, [record('BTC'), record('ETH')])
                self.assertEqual(self.stored_tokens(table), ['BTC', 'ETH'])
                self.assert_reported(scraper, 2, result, output)

    def test_bad_rows_do_not_erase_good_rows(self):
        batches = (
            [None, 'BTC', 'ETH'],
            ['BTC', None, 'ETH'],
            ['BTC', 'ETH', None],
            ['BTC', None, None, 'ETH'],
        )
        for cls, table in SCRAPERS:
            for tokens in batches:
                with self.subTest(scraper=cls.__name__, tokens=tokens):
                    self.clear_table(table)
                    scraper = self.scraper(cls)
                    result, output = self.save(scraper, [record(t) for t in tokens])
                    self.assertEqual(self.stored_tokens(table), ['BTC', 'ETH'])
                    self.assert_reported(scraper, 2, result, output)

    def test_missing_field_does_not_erase_good_rows(self):
        bad_record = record('BAD')
        del bad_record['token']
        for cls, table in SCRAPERS:
            with self.subTest(scraper=cls.__name__):
                scraper = self.scraper(cls)
                result, output = self.save(scraper, [record('BTC'), bad_record, record('ETH')])
                self.assertEqual(self.stored_tokens(table), ['BTC', 'ETH'])
                self.assert_reported(scraper, 2, result, output)

    def test_all_invalid_rows_leave_connection_ready_for_next_batch(self):
        for cls, table in SCRAPERS:
            with self.subTest(scraper=cls.__name__):
                scraper = self.scraper(cls)
                result, output = self.save(scraper, [record(None), record(None)])
                self.assert_reported(scraper, 0, result, output)
                self.assertEqual(self.conn.get_transaction_status(), TRANSACTION_STATUS_IDLE)
                self.assertEqual(self.stored_tokens(table), [])
                result, output = self.save(scraper, [record('BTC')])
                self.assertEqual(self.stored_tokens(table), ['BTC'])
                self.assert_reported(scraper, 1, result, output)

    def test_failed_commit_does_not_report_saved_rows(self):
        for cls, table in SCRAPERS:
            with self.subTest(scraper=cls.__name__):
                self.reject_at_commit(table)
                scraper = self.scraper(cls)
                records = [record('BTC'), record('ETH')]
                result, output = self.save(scraper, records)
                self.assert_reported(scraper, 0, result, output)
                self.assertEqual(self.conn.get_transaction_status(), TRANSACTION_STATUS_IDLE)
                self.assertEqual(self.stored_tokens(table), [])
                if isinstance(scraper, LiquidationScraper):
                    self.assertEqual(scraper.pending_liquidations, records)

    def test_connection_can_save_after_a_failed_commit(self):
        for cls, table in SCRAPERS:
            with self.subTest(scraper=cls.__name__):
                self.reject_at_commit(table)
                scraper = self.scraper(cls)
                self.save(scraper, [record('BTC')])
                # Do not repair the connection in the test before reusing it
                self.remove_commit_failure(table)
                result, output = self.save(scraper, [record('ETH')])
                self.assertEqual(self.stored_tokens(table), ['ETH'])
                self.assert_reported(scraper, 1, result, output)

    def test_ohlcv_update_survives_a_later_bad_record(self):
        scraper = self.scraper(BinanceOHLCVScraper)
        self.save(scraper, [record('BTC')])
        updated = record('BTC')
        updated['close'] = 108
        result, output = self.save(scraper, [updated, record(None)])
        self.assert_reported(scraper, 1, result, output)
        self.conn.rollback()
        with self.conn.cursor() as cursor:
            cursor.execute("SELECT close FROM crypto_ohlcv WHERE token = 'BTC'")
            self.assertEqual(cursor.fetchone()[0], 108)

    def test_ohlcv_count_includes_successful_updates(self):
        scraper = self.scraper(BinanceOHLCVScraper)
        updated = record('BTC')
        updated['close'] = 108
        result, output = self.save(scraper, [record('BTC'), updated])
        self.assertEqual(self.stored_tokens('crypto_ohlcv'), ['BTC'])
        self.assert_reported(scraper, 2, result, output)

    def test_liquidation_summary_uses_only_saved_records(self):
        scraper = self.scraper(LiquidationScraper)
        bad_record = record('BAD')
        bad_record['price'] = 'not a number'
        _, output = self.save(scraper, [record('BTC'), bad_record, record('ETH')])
        self.assertEqual(self.stored_tokens('liquidations'), ['BTC', 'ETH'])
        self.assertIn('Saved 2 liquidations', output)
        self.assertNotIn('\n  BAD ', output)
        self.assertEqual(scraper.pending_liquidations, [])

    def test_liquidations_retry_pending_rows_after_commit_failure(self):
        self.reject_at_commit('liquidations')
        scraper = self.scraper(LiquidationScraper)
        records = [record('BTC'), record('ETH')]
        self.save(scraper, records)
        self.assertEqual(scraper.pending_liquidations, records)
        self.remove_commit_failure('liquidations')
        with redirect_stdout(io.StringIO()):
            scraper.save_to_db()
        self.assertEqual(self.stored_tokens('liquidations'), ['BTC', 'ETH'])
        self.assertEqual(scraper.pending_liquidations, [])


if __name__ == '__main__':
    unittest.main()
