import logging
import os
from pathlib import Path
import re
import sys
from datetime import datetime, timezone
from types import ModuleType, SimpleNamespace
import unittest
from unittest.mock import Mock, patch
from uuid import uuid4

import psycopg2
from psycopg2 import sql


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


class RequestError(Exception):
    pass


# Database tests do not fetch feeds, call NewsAPI, or read local credentials
external_modules = {
    name: ModuleType(name) for name in ('feedparser', 'schedule', 'dotenv', 'requests')
}
external_modules['dotenv'].load_dotenv = lambda: None
external_modules['requests'].get = Mock(side_effect=AssertionError('Unexpected API request'))
external_modules['requests'].exceptions = SimpleNamespace(RequestException=RequestError)
with patch.dict(sys.modules, external_modules), patch.dict(os.environ, {'NEWS_API_KEY': 'test-key'}):
    from news_scrapers import rss_aggregator, newsapi_reader


WRITERS = (rss_aggregator, newsapi_reader)


def article(number):
    return {
        'title': f'Article {number}',
        'content': f'Content for article {number}',
        'url': f'https://example.com/news/{number}',
        'source': 'Test feed',
        'published_at': datetime(2026, 1, 1, tzinfo=timezone.utc),
    }


class NewsSaveTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.database_url = os.environ.get('TEST_DATABASE_URL')
        if not cls.database_url:
            raise RuntimeError('Set TEST_DATABASE_URL to a disposable PostgreSQL database.')

    def setUp(self):
        self.schema_name = 'test_news_saves_' + uuid4().hex
        self.app_connections = []
        self.addCleanup(self.drop_schema)
        schema = (ROOT / 'data/pjx_database_schema.sql').read_text(encoding='utf-8')
        match = re.search(r'CREATE TABLE public\.news_articles \((.*?)\n\);', schema, re.DOTALL)
        self.assertIsNotNone(match)

        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(self.schema_name)))
                cursor.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(
                    sql.Identifier(self.schema_name)
                ))
                cursor.execute(sql.SQL('CREATE TABLE news_articles ({})').format(sql.SQL(match.group(1))))
                cursor.execute('ALTER TABLE news_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')
                cursor.execute('ALTER TABLE news_articles ADD PRIMARY KEY (id)')
                cursor.execute('ALTER TABLE news_articles ADD UNIQUE (url)')
            conn.commit()
        finally:
            conn.close()

    def connect(self):
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(
                    sql.Identifier(self.schema_name)
                ))
            conn.commit()
        except Exception:
            conn.close()
            raise
        return conn

    def app_connection(self):
        conn = self.connect()
        self.app_connections.append(conn)
        self.addCleanup(conn.close)
        return conn

    def query(self, statement):
        conn = self.connect()
        try:
            with conn.cursor() as cursor:
                cursor.execute(statement)
                rows = cursor.fetchall() if cursor.description else None
            conn.commit()
            return rows
        finally:
            conn.close()

    def drop_schema(self):
        conn = psycopg2.connect(self.database_url, connect_timeout=10)
        try:
            with conn.cursor() as cursor:
                cursor.execute(sql.SQL('DROP SCHEMA IF EXISTS {} CASCADE').format(
                    sql.Identifier(self.schema_name)
                ))
            conn.commit()
        finally:
            conn.close()

    def store(self, writer, articles):
        api_articles = [
            {
                'title': item['title'], 'url': item['url'],
                'description': item['content'], 'source': {'name': item['source']},
                'publishedAt': item['published_at'].isoformat(),
            }
            for item in articles
        ]
        response = Mock()
        response.json.return_value = {'status': 'ok', 'articles': api_articles}
        with patch.object(writer, 'get_db_connection', side_effect=self.app_connection), \
                patch.object(newsapi_reader.requests, 'get', return_value=response), \
                patch.object(logging, 'info') as info, patch.object(logging, 'error') as error:
            if writer is rss_aggregator:
                result = writer.store_articles(articles)
            else:
                result = writer.fetch_and_store_news()
        self.assertTrue(all(conn.closed for conn in self.app_connections))
        return result, [call.args[0] for call in info.call_args_list], [call.args[0] for call in error.call_args_list]

    def assert_reported(self, writer, expected, result, messages, committed=True):
        if writer is rss_aggregator:
            self.assertEqual(result, expected)
        elif committed:
            self.assertIn(f'Added {expected} new articles to PostgreSQL.', messages)
        else:
            self.assertFalse(any(message.startswith('Added ') for message in messages))

    def stored_urls(self):
        # Read through a new connection after the writer has closed its own
        return [row[0] for row in self.query('SELECT url FROM news_articles ORDER BY url')]

    def test_fourth_rejected_article_keeps_the_other_five(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                self.query('TRUNCATE news_articles')
                articles = [article(i) for i in range(1, 7)]
                articles[3]['source'] = 'x' * 101
                result, messages, errors = self.store(writer, articles)
                expected = [item['url'] for i, item in enumerate(articles) if i != 3]
                self.assertEqual(self.stored_urls(), expected)
                self.assert_reported(writer, 5, result, messages)
                self.assertEqual(len(errors), 1)
                self.assertIn('value too long', errors[0])
                self.assertNotIn('current transaction is aborted', errors[0])

    def test_rejected_first_or_last_article_does_not_poison_batch(self):
        for writer in WRITERS:
            for bad_index in (0, 2):
                with self.subTest(writer=writer.__name__, bad_index=bad_index):
                    self.query('TRUNCATE news_articles')
                    articles = [article(i) for i in range(1, 4)]
                    articles[bad_index]['source'] = 'x' * 101
                    result, messages, errors = self.store(writer, articles)
                    expected = [item['url'] for i, item in enumerate(articles) if i != bad_index]
                    self.assertEqual(self.stored_urls(), expected)
                    self.assert_reported(writer, 2, result, messages)
                    self.assertEqual(len(errors), 1)

    def test_duplicates_are_not_counted_after_a_rejected_article(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                self.query('TRUNCATE news_articles')
                self.store(writer, [article(1)])
                bad = article(3)
                bad['source'] = 'x' * 101
                result, messages, _ = self.store(writer, [article(1), article(2), bad, article(2), article(4)])
                self.assertEqual(self.stored_urls(), [article(i)['url'] for i in (1, 2, 4)])
                self.assert_reported(writer, 2, result, messages)

    def test_long_title_is_preserved_with_the_committed_schema(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                self.query('TRUNCATE news_articles')
                item = article(1)
                item['title'] = 'x' * 300
                result, messages, _ = self.store(writer, [item])
                self.assertEqual(self.query('SELECT title FROM news_articles'), [(item['title'],)])
                self.assert_reported(writer, 1, result, messages)

    def test_all_rejected_articles_report_zero_without_cascading_errors(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                self.query('TRUNCATE news_articles')
                articles = [article(1), article(2)]
                for item in articles:
                    item['source'] = 'x' * 101
                result, messages, errors = self.store(writer, articles)
                self.assertEqual(self.stored_urls(), [])
                self.assert_reported(writer, 0, result, messages)
                self.assertEqual(len(errors), 2)
                self.assertTrue(all('value too long' in message for message in errors))

    def test_failed_commit_does_not_claim_saved_articles(self):
        self.query('''
            CREATE FUNCTION reject_news_commit() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'test commit failure';
            END;
            $$;
            CREATE CONSTRAINT TRIGGER reject_news_commit
            AFTER INSERT ON news_articles DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION reject_news_commit();
        ''')
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                result, messages, errors = self.store(writer, [article(1), article(2)])
                self.assertEqual(self.stored_urls(), [])
                self.assert_reported(writer, 0, result, messages, committed=False)
                self.assertTrue(any('test commit failure' in message for message in errors))

    def test_empty_batch_reports_zero(self):
        for writer in WRITERS:
            with self.subTest(writer=writer.__name__):
                result, messages, _ = self.store(writer, [])
                self.assertEqual(self.stored_urls(), [])
                self.assert_reported(writer, 0, result, messages)

    def test_newsapi_row_error_after_insert_is_not_counted(self):
        articles = [article(i) for i in range(1, 4)]
        articles[1]['title'] = 123
        result, messages, errors = self.store(newsapi_reader, articles)
        self.assertEqual(self.stored_urls(), [article(1)['url'], article(3)['url']])
        self.assert_reported(newsapi_reader, 2, result, messages)
        self.assertEqual(len(errors), 1)


if __name__ == '__main__':
    unittest.main()
