-- ============================================================================
-- PJX CRYPTO TRADING SYSTEM - COMPLETE DATABASE SCHEMA
-- Auto-generated via pg_dump from running Docker Postgres
-- Command: docker exec pjx-postgres pg_dump -U postgres --schema-only pjx
-- Date: autogenerated snapshot
-- ============================================================================

--
-- PostgreSQL database dump
--

\restrict FCHgTsLP6K3LdVfb7hlNmqkL3NsMTCu1Bgfi4xHr7T4mpP9g6xVEVnpmCjbeG7m

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: calculate_flow_velocity(character varying, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.calculate_flow_velocity(p_chain character varying, p_days integer DEFAULT 7) RETURNS TABLE(velocity numeric, acceleration numeric, trend character varying)
    LANGUAGE plpgsql
    AS $$
DECLARE
    current_period_flow DECIMAL(18, 2);
    previous_period_flow DECIMAL(18, 2);
    velocity_value DECIMAL(18, 2);
    acceleration_value DECIMAL(18, 2);
    trend_value VARCHAR(20);
BEGIN
    -- Calculate current period flow
    SELECT SUM(net_flow_usd) INTO current_period_flow
    FROM bridge_flows
    WHERE chain = p_chain
    AND date > CURRENT_DATE - INTERVAL '1 day' * p_days
    AND date <= CURRENT_DATE;

    -- Calculate previous period flow
    SELECT SUM(net_flow_usd) INTO previous_period_flow
    FROM bridge_flows
    WHERE chain = p_chain
    AND date > CURRENT_DATE - INTERVAL '1 day' * (p_days * 2)
    AND date <= CURRENT_DATE - INTERVAL '1 day' * p_days;

    -- Calculate velocity (rate of change)
    IF previous_period_flow IS NOT NULL AND previous_period_flow != 0 THEN
        velocity_value := ((current_period_flow - previous_period_flow) / ABS(previous_period_flow)) * 100;
    ELSE
        velocity_value := 0;
    END IF;

    -- Simple acceleration (change in velocity)
    acceleration_value := current_period_flow - COALESCE(previous_period_flow, 0);

    -- Determine trend
    IF velocity_value > 50 THEN
        trend_value := 'ACCELERATING';
    ELSIF velocity_value > 10 THEN
        trend_value := 'INCREASING';
    ELSIF velocity_value < -50 THEN
        trend_value := 'DECELERATING';
    ELSIF velocity_value < -10 THEN
        trend_value := 'DECREASING';
    ELSE
        trend_value := 'STABLE';
    END IF;

    RETURN QUERY SELECT velocity_value, acceleration_value, trend_value;
END;
$$;


ALTER FUNCTION public.calculate_flow_velocity(p_chain character varying, p_days integer) OWNER TO postgres;

--
-- Name: detect_rotation_signals(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.detect_rotation_signals() RETURNS TABLE(chain character varying, signal_strength character varying, net_flow_7d numeric, velocity numeric, recommendation character varying)
    LANGUAGE plpgsql
    AS $$
BEGIN
    RETURN QUERY
    WITH flow_analysis AS (
        SELECT
            bf.chain,
            SUM(CASE WHEN bf.date >= CURRENT_DATE - INTERVAL '7 days' THEN bf.net_flow_usd ELSE 0 END) as flow_7d,
            (SELECT velocity FROM calculate_flow_velocity(bf.chain, 7)) as vel
        FROM bridge_flows bf
        WHERE bf.date >= CURRENT_DATE - INTERVAL '7 days'
        GROUP BY bf.chain
    )
    SELECT
        fa.chain,
        CASE
            WHEN fa.flow_7d > 100000000 AND fa.vel > 50 THEN 'VERY_STRONG'
            WHEN fa.flow_7d > 50000000 AND fa.vel > 25 THEN 'STRONG'
            WHEN fa.flow_7d > 10000000 AND fa.vel > 0 THEN 'MODERATE'
            WHEN fa.flow_7d < -50000000 THEN 'NEGATIVE'
            ELSE 'WEAK'
        END as signal_strength,
        fa.flow_7d as net_flow_7d,
        fa.vel as velocity,
        CASE
            WHEN fa.flow_7d > 100000000 AND fa.vel > 50 THEN
                'Strong capital rotation into ' || fa.chain || '. Consider accumulating ecosystem tokens.'
            WHEN fa.flow_7d > 50000000 AND fa.vel > 25 THEN
                'Significant inflows to ' || fa.chain || '. Monitor for entry opportunities.'
            WHEN fa.flow_7d > 10000000 AND fa.vel > 0 THEN
                'Moderate inflows to ' || fa.chain || '. Watch for trend continuation.'
            WHEN fa.flow_7d < -50000000 THEN
                'Major outflows from ' || fa.chain || '. Consider reducing exposure.'
            ELSE
                'Neutral flow for ' || fa.chain || '. No immediate action required.'
        END as recommendation
    FROM flow_analysis fa
    WHERE fa.flow_7d IS NOT NULL
    ORDER BY fa.flow_7d DESC;
END;
$$;


ALTER FUNCTION public.detect_rotation_signals() OWNER TO postgres;

--
-- Name: FUNCTION detect_rotation_signals(); Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON FUNCTION public.detect_rotation_signals() IS 'Returns actionable trading signals based on bridge flows';


--
-- Name: get_volatility_risk_score(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.get_volatility_risk_score() RETURNS TABLE(risk_score integer, risk_components jsonb)
    LANGUAGE plpgsql
    AS $$
DECLARE
    latest_record RECORD;
    score INTEGER := 0;
    components JSONB := '{}';
BEGIN
    -- Get latest options data
    SELECT * INTO latest_record
    FROM options_volatility
    ORDER BY scraped_at DESC
    LIMIT 1;

    IF latest_record IS NULL THEN
        RETURN QUERY SELECT 0, '{}'::JSONB;
        RETURN;
    END IF;

    -- Score based on average IV (0-40 points)
    IF latest_record.avg_iv > 80 THEN
        score := score + 40;
        components := components || '{"iv_score": 40}';
    ELSIF latest_record.avg_iv > 65 THEN
        score := score + 25;
        components := components || '{"iv_score": 25}';
    ELSIF latest_record.avg_iv > 50 THEN
        score := score + 10;
        components := components || '{"iv_score": 10}';
    END IF;

    -- Score based on skew (0-30 points)
    IF latest_record.btc_skew < -10 OR latest_record.eth_skew < -10 THEN
        score := score + 30;
        components := components || '{"skew_score": 30}';
    ELSIF latest_record.btc_skew < -5 OR latest_record.eth_skew < -5 THEN
        score := score + 15;
        components := components || '{"skew_score": 15}';
    END IF;

    -- Score based on IV rank (0-30 points)
    IF latest_record.btc_iv_rank > 80 OR latest_record.eth_iv_rank > 80 THEN
        score := score + 30;
        components := components || '{"iv_rank_score": 30}';
    ELSIF latest_record.btc_iv_rank > 60 OR latest_record.eth_iv_rank > 60 THEN
        score := score + 15;
        components := components || '{"iv_rank_score": 15}';
    END IF;

    components := components || jsonb_build_object(
        'total_score', score,
        'btc_iv', latest_record.btc_iv,
        'eth_iv', latest_record.eth_iv,
        'avg_iv', latest_record.avg_iv,
        'btc_skew', latest_record.btc_skew,
        'eth_skew', latest_record.eth_skew
    );

    RETURN QUERY SELECT score, components;
END;
$$;


ALTER FUNCTION public.get_volatility_risk_score() OWNER TO postgres;

--
-- Name: refresh_twitter_volume(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.refresh_twitter_volume() RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY hourly_twitter_volume;
END;
$$;


ALTER FUNCTION public.refresh_twitter_volume() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bridge_flow_signals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bridge_flow_signals (
    id integer NOT NULL,
    signal_type character varying(50) NOT NULL,
    chain character varying(50),
    timeframe character varying(20),
    metric_name character varying(50),
    metric_value numeric(18,2),
    threshold numeric(18,2),
    interpretation character varying(200),
    alert_level character varying(20),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.bridge_flow_signals OWNER TO postgres;

--
-- Name: bridge_flow_signals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bridge_flow_signals_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bridge_flow_signals_id_seq OWNER TO postgres;

--
-- Name: bridge_flow_signals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.bridge_flow_signals_id_seq OWNED BY public.bridge_flow_signals.id;


--
-- Name: bridge_flows; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bridge_flows (
    id integer NOT NULL,
    chain character varying(50) NOT NULL,
    date date NOT NULL,
    deposits_usd numeric(18,2),
    withdrawals_usd numeric(18,2),
    net_flow_usd numeric(18,2) GENERATED ALWAYS AS ((deposits_usd - withdrawals_usd)) STORED,
    deposit_txs integer,
    withdraw_txs integer,
    total_txs integer GENERATED ALWAYS AS ((deposit_txs + withdraw_txs)) STORED,
    scraped_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.bridge_flows OWNER TO postgres;

--
-- Name: TABLE bridge_flows; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.bridge_flows IS 'DeFiLlama bridge flow data for L1/L2 capital rotation tracking';


--
-- Name: bridge_flows_7d; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.bridge_flows_7d AS
 SELECT chain,
    sum(deposits_usd) AS deposits_7d,
    sum(withdrawals_usd) AS withdrawals_7d,
    sum(net_flow_usd) AS net_flow_7d,
    avg(net_flow_usd) AS avg_daily_flow,
    count(DISTINCT date) AS days_tracked,
    max(date) AS latest_date
   FROM public.bridge_flows
  WHERE (date >= (CURRENT_DATE - '7 days'::interval))
  GROUP BY chain
  ORDER BY (sum(net_flow_usd)) DESC;


ALTER VIEW public.bridge_flows_7d OWNER TO postgres;

--
-- Name: bridge_flows_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bridge_flows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bridge_flows_id_seq OWNER TO postgres;

--
-- Name: bridge_flows_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.bridge_flows_id_seq OWNED BY public.bridge_flows.id;


--
-- Name: bridge_flows_latest; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.bridge_flows_latest AS
 SELECT chain,
    date,
    deposits_usd,
    withdrawals_usd,
    net_flow_usd,
    deposit_txs,
    withdraw_txs,
        CASE
            WHEN (net_flow_usd > (10000000)::numeric) THEN 'STRONG_INFLOW'::text
            WHEN (net_flow_usd > (1000000)::numeric) THEN 'MODERATE_INFLOW'::text
            WHEN (net_flow_usd < ('-10000000'::integer)::numeric) THEN 'STRONG_OUTFLOW'::text
            WHEN (net_flow_usd < ('-1000000'::integer)::numeric) THEN 'MODERATE_OUTFLOW'::text
            ELSE 'NEUTRAL'::text
        END AS flow_status
   FROM public.bridge_flows
  WHERE (((chain)::text, date) IN ( SELECT bridge_flows_1.chain,
            max(bridge_flows_1.date) AS max_date
           FROM public.bridge_flows bridge_flows_1
          GROUP BY bridge_flows_1.chain))
  ORDER BY net_flow_usd DESC;


ALTER VIEW public.bridge_flows_latest OWNER TO postgres;

--
-- Name: circuit_breaker_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.circuit_breaker_events (
    id integer NOT NULL,
    event_type character varying(50) NOT NULL,
    triggered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    reason text NOT NULL,
    portfolio_value numeric(12,2),
    daily_drawdown numeric(8,4),
    consecutive_losses integer,
    auto_resume_at timestamp with time zone
);


ALTER TABLE public.circuit_breaker_events OWNER TO postgres;

--
-- Name: circuit_breaker_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.circuit_breaker_events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.circuit_breaker_events_id_seq OWNER TO postgres;

--
-- Name: circuit_breaker_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.circuit_breaker_events_id_seq OWNED BY public.circuit_breaker_events.id;


--
-- Name: company_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_profiles (
    id integer NOT NULL,
    symbol character varying(10) NOT NULL,
    company_name character varying(255),
    exchange character varying(50),
    industry character varying(255),
    sector character varying(255),
    market_cap bigint,
    beta numeric(10,4),
    pe_ratio numeric(10,4),
    eps numeric(10,4),
    website text,
    last_updated timestamp with time zone
);


ALTER TABLE public.company_profiles OWNER TO postgres;

--
-- Name: company_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.company_profiles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.company_profiles_id_seq OWNER TO postgres;

--
-- Name: company_profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.company_profiles_id_seq OWNED BY public.company_profiles.id;


--
-- Name: congressional_trades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.congressional_trades (
    id integer NOT NULL,
    source character varying(10),
    filer_name character varying(255),
    filing_date date,
    transaction_date date,
    ticker character varying(50),
    transaction_type character varying(50),
    amount_range character varying(100),
    report_url text,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.congressional_trades OWNER TO postgres;

--
-- Name: congressional_trades_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.congressional_trades_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.congressional_trades_id_seq OWNER TO postgres;

--
-- Name: congressional_trades_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.congressional_trades_id_seq OWNED BY public.congressional_trades.id;


--
-- Name: crypto_ohlcv; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crypto_ohlcv (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    timeframe character varying(10) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    open numeric(20,8) NOT NULL,
    high numeric(20,8) NOT NULL,
    low numeric(20,8) NOT NULL,
    close numeric(20,8) NOT NULL,
    volume numeric(30,8) NOT NULL,
    source character varying(50) DEFAULT 'binance'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.crypto_ohlcv OWNER TO postgres;

--
-- Name: crypto_ohlcv_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.crypto_ohlcv_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.crypto_ohlcv_id_seq OWNER TO postgres;

--
-- Name: crypto_ohlcv_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.crypto_ohlcv_id_seq OWNED BY public.crypto_ohlcv.id;


--
-- Name: defi_protocols; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defi_protocols (
    id integer NOT NULL,
    protocol_name character varying(100) NOT NULL,
    symbol character varying(20),
    tvl_usd numeric(20,2) NOT NULL,
    change_1d_pct numeric(8,2),
    change_7d_pct numeric(8,2),
    category character varying(50),
    main_chain character varying(50),
    all_chains jsonb,
    market_cap numeric(20,2),
    tvl_to_mcap_ratio numeric(8,4),
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.defi_protocols OWNER TO postgres;

--
-- Name: defi_flow_alerts; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.defi_flow_alerts AS
 WITH recent_data AS (
         SELECT defi_protocols.protocol_name,
            defi_protocols.tvl_usd,
            defi_protocols.change_1d_pct,
            defi_protocols.category,
            defi_protocols.scraped_at
           FROM public.defi_protocols
          WHERE (defi_protocols.scraped_at > (now() - '01:00:00'::interval))
        )
 SELECT protocol_name,
    tvl_usd,
    change_1d_pct,
    category,
        CASE
            WHEN ((change_1d_pct > (20)::numeric) AND (tvl_usd > (100000000)::numeric)) THEN 'MASSIVE_INFLOW'::text
            WHEN ((change_1d_pct > (10)::numeric) AND (tvl_usd > (500000000)::numeric)) THEN 'LARGE_INFLOW'::text
            WHEN ((change_1d_pct < ('-20'::integer)::numeric) AND (tvl_usd > (100000000)::numeric)) THEN 'MASSIVE_OUTFLOW'::text
            WHEN ((change_1d_pct < ('-10'::integer)::numeric) AND (tvl_usd > (500000000)::numeric)) THEN 'LARGE_OUTFLOW'::text
            ELSE 'NORMAL'::text
        END AS alert_type,
    scraped_at
   FROM recent_data
  WHERE (abs(change_1d_pct) > (10)::numeric)
  ORDER BY (abs(change_1d_pct)) DESC;


ALTER VIEW public.defi_flow_alerts OWNER TO postgres;

--
-- Name: defi_flow_signals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defi_flow_signals (
    id integer NOT NULL,
    biggest_gainers jsonb,
    biggest_losers jsonb,
    category_flows jsonb,
    risk_indicator character varying(50),
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.defi_flow_signals OWNER TO postgres;

--
-- Name: defi_flow_signals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.defi_flow_signals_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.defi_flow_signals_id_seq OWNER TO postgres;

--
-- Name: defi_flow_signals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.defi_flow_signals_id_seq OWNED BY public.defi_flow_signals.id;


--
-- Name: defi_protocols_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.defi_protocols_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.defi_protocols_id_seq OWNER TO postgres;

--
-- Name: defi_protocols_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.defi_protocols_id_seq OWNED BY public.defi_protocols.id;


--
-- Name: defi_tvl_chains; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defi_tvl_chains (
    id integer NOT NULL,
    chain_name character varying(50) NOT NULL,
    tvl_usd numeric(20,2) NOT NULL,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.defi_tvl_chains OWNER TO postgres;

--
-- Name: defi_tvl_chains_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.defi_tvl_chains_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.defi_tvl_chains_id_seq OWNER TO postgres;

--
-- Name: defi_tvl_chains_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.defi_tvl_chains_id_seq OWNED BY public.defi_tvl_chains.id;


--
-- Name: defi_tvl_latest; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.defi_tvl_latest AS
 WITH latest_chains AS (
         SELECT DISTINCT ON (defi_tvl_chains.chain_name) defi_tvl_chains.chain_name,
            defi_tvl_chains.tvl_usd,
            defi_tvl_chains.scraped_at
           FROM public.defi_tvl_chains
          ORDER BY defi_tvl_chains.chain_name, defi_tvl_chains.scraped_at DESC
        ), latest_protocols AS (
         SELECT DISTINCT ON (defi_protocols.protocol_name) defi_protocols.protocol_name,
            defi_protocols.symbol,
            defi_protocols.tvl_usd,
            defi_protocols.change_1d_pct,
            defi_protocols.change_7d_pct,
            defi_protocols.category,
            defi_protocols.main_chain,
            defi_protocols.scraped_at
           FROM public.defi_protocols
          ORDER BY defi_protocols.protocol_name, defi_protocols.scraped_at DESC
        )
 SELECT ( SELECT sum(latest_chains.tvl_usd) AS sum
           FROM latest_chains) AS total_tvl,
    ( SELECT json_object_agg(latest_chains.chain_name, latest_chains.tvl_usd) AS json_object_agg
           FROM latest_chains) AS chain_breakdown,
    ( SELECT count(*) AS count
           FROM latest_protocols
          WHERE (latest_protocols.change_1d_pct > (5)::numeric)) AS protocols_gaining,
    ( SELECT count(*) AS count
           FROM latest_protocols
          WHERE (latest_protocols.change_1d_pct < ('-5'::integer)::numeric)) AS protocols_losing,
    ( SELECT max(latest_chains.scraped_at) AS max
           FROM latest_chains) AS last_updated;


ALTER VIEW public.defi_tvl_latest OWNER TO postgres;

--
-- Name: dex_liquidity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dex_liquidity (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    dex_name character varying(50) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    liquidity_usd numeric(20,2),
    volume_24h numeric(20,2),
    volume_change_24h numeric(10,4),
    price_usd numeric(20,10),
    price_change_24h numeric(10,4),
    pool_count integer,
    fdv numeric(20,2),
    market_cap numeric(20,2),
    volume_to_liquidity_ratio numeric(10,4),
    liquidity_change_24h numeric(10,4),
    source character varying(50) DEFAULT 'dexscreener'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.dex_liquidity OWNER TO postgres;

--
-- Name: dex_liquidity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.dex_liquidity_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dex_liquidity_id_seq OWNER TO postgres;

--
-- Name: dex_liquidity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.dex_liquidity_id_seq OWNED BY public.dex_liquidity.id;


--
-- Name: economic_indicators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.economic_indicators (
    id integer NOT NULL,
    indicator_code character varying(20) NOT NULL,
    date date NOT NULL,
    value numeric NOT NULL,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.economic_indicators OWNER TO postgres;

--
-- Name: economic_indicators_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.economic_indicators_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.economic_indicators_id_seq OWNER TO postgres;

--
-- Name: economic_indicators_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.economic_indicators_id_seq OWNED BY public.economic_indicators.id;


--
-- Name: ensemble_votes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ensemble_votes (
    id integer NOT NULL,
    decision_id integer,
    model_name character varying(50) NOT NULL,
    vote character varying(10) NOT NULL,
    confidence numeric(5,4),
    reasoning text,
    response_time_ms integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ensemble_votes OWNER TO postgres;

--
-- Name: ensemble_votes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ensemble_votes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ensemble_votes_id_seq OWNER TO postgres;

--
-- Name: ensemble_votes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ensemble_votes_id_seq OWNED BY public.ensemble_votes.id;


--
-- Name: exchange_flows; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exchange_flows (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    flow_type character varying(20) NOT NULL,
    amount numeric(20,8) NOT NULL,
    usd_value numeric(20,2),
    exchange character varying(50),
    transaction_hash character varying(100),
    "timestamp" timestamp with time zone NOT NULL,
    source character varying(50) DEFAULT 'blockchain'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    from_address character varying(100),
    to_address character varying(100),
    from_entity character varying(100),
    to_entity character varying(100),
    is_smart_money boolean DEFAULT false,
    smart_money_type character varying(50),
    signal_strength numeric(3,2)
);


ALTER TABLE public.exchange_flows OWNER TO postgres;

--
-- Name: exchange_flows_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.exchange_flows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exchange_flows_id_seq OWNER TO postgres;

--
-- Name: exchange_flows_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.exchange_flows_id_seq OWNED BY public.exchange_flows.id;


--
-- Name: fear_greed_index; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fear_greed_index (
    id integer NOT NULL,
    value integer NOT NULL,
    classification character varying(20),
    "timestamp" timestamp with time zone NOT NULL,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.fear_greed_index OWNER TO postgres;

--
-- Name: fear_greed_index_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fear_greed_index_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fear_greed_index_id_seq OWNER TO postgres;

--
-- Name: fear_greed_index_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fear_greed_index_id_seq OWNED BY public.fear_greed_index.id;


--
-- Name: funding_rates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funding_rates (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    funding_rate numeric(10,6) NOT NULL,
    next_funding_time timestamp with time zone,
    mark_price numeric(20,8),
    index_price numeric(20,8),
    source character varying(50) DEFAULT 'binance'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.funding_rates OWNER TO postgres;

--
-- Name: funding_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.funding_rates_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.funding_rates_id_seq OWNER TO postgres;

--
-- Name: funding_rates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.funding_rates_id_seq OWNED BY public.funding_rates.id;


--
-- Name: twitter_sentiment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.twitter_sentiment (
    id integer NOT NULL,
    tweet_id character varying(50) NOT NULL,
    token character varying(20) NOT NULL,
    tweet_text text NOT NULL,
    sentiment_score numeric(5,4),
    sentiment_label character varying(20),
    author_username character varying(100),
    author_followers integer,
    retweet_count integer DEFAULT 0,
    like_count integer DEFAULT 0,
    reply_count integer DEFAULT 0,
    quote_count integer DEFAULT 0,
    tweet_created_at timestamp with time zone,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    weighted_score numeric(10,4),
    alert_level character varying(20),
    is_whale boolean DEFAULT false,
    volume_spike numeric(5,2),
    bot_probability numeric(4,3),
    pump_score numeric(4,3),
    influence_weight numeric(10,4),
    source character varying(50) DEFAULT 'general_search'::character varying,
    verified boolean DEFAULT false,
    has_urls boolean DEFAULT false,
    hashtag_count integer DEFAULT 0,
    following_count integer DEFAULT 0,
    sentiment_velocity numeric(10,6),
    volume_acceleration numeric(10,6),
    momentum_score numeric(10,6),
    CONSTRAINT chk_bot_probability CHECK (((bot_probability >= (0)::numeric) AND (bot_probability <= (1)::numeric))),
    CONSTRAINT chk_influence_weight CHECK (((influence_weight >= (0)::numeric) AND (influence_weight <= (1)::numeric))),
    CONSTRAINT chk_pump_score CHECK (((pump_score >= (0)::numeric) AND (pump_score <= (1)::numeric))),
    CONSTRAINT chk_sentiment_score CHECK (((sentiment_score >= ('-1'::integer)::numeric) AND (sentiment_score <= (1)::numeric))),
    CONSTRAINT chk_volume_spike CHECK ((volume_spike >= (0)::numeric))
);


ALTER TABLE public.twitter_sentiment OWNER TO postgres;

--
-- Name: hourly_twitter_volume; Type: MATERIALIZED VIEW; Schema: public; Owner: postgres
--

CREATE MATERIALIZED VIEW public.hourly_twitter_volume AS
 SELECT date_trunc('hour'::text, scraped_at) AS hour,
    token,
    count(*) AS tweet_count,
    count(*) FILTER (WHERE (bot_probability < 0.5)) AS human_tweets,
    avg(sentiment_score) AS avg_sentiment,
    avg(
        CASE
            WHEN (bot_probability < 0.5) THEN sentiment_score
            ELSE NULL::numeric
        END) AS human_sentiment,
    max(volume_spike) AS max_volume_spike,
    avg(weighted_score) AS avg_weighted,
    max(weighted_score) AS max_weighted,
    count(*) FILTER (WHERE ((alert_level)::text = ANY ((ARRAY['HIGH'::character varying, 'EXTREME'::character varying, 'WHALE_SIGNAL'::character varying])::text[]))) AS high_impact_count
   FROM public.twitter_sentiment
  WHERE (scraped_at > (now() - '7 days'::interval))
  GROUP BY (date_trunc('hour'::text, scraped_at)), token
  WITH NO DATA;


ALTER MATERIALIZED VIEW public.hourly_twitter_volume OWNER TO postgres;

--
-- Name: l2_rotation_rankings; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.l2_rotation_rankings AS
 WITH flow_metrics AS (
         SELECT bridge_flows.chain,
            sum(
                CASE
                    WHEN (bridge_flows.date = (CURRENT_DATE - '1 day'::interval)) THEN bridge_flows.net_flow_usd
                    ELSE (0)::numeric
                END) AS flow_24h,
            sum(
                CASE
                    WHEN (bridge_flows.date >= (CURRENT_DATE - '7 days'::interval)) THEN bridge_flows.net_flow_usd
                    ELSE (0)::numeric
                END) AS flow_7d,
            sum(
                CASE
                    WHEN (bridge_flows.date >= (CURRENT_DATE - '30 days'::interval)) THEN bridge_flows.net_flow_usd
                    ELSE (0)::numeric
                END) AS flow_30d,
                CASE
                    WHEN (count(
                    CASE
                        WHEN (bridge_flows.date >= (CURRENT_DATE - '30 days'::interval)) THEN 1
                        ELSE NULL::integer
                    END) >= 7) THEN ((sum(
                    CASE
                        WHEN (bridge_flows.date >= (CURRENT_DATE - '7 days'::interval)) THEN bridge_flows.net_flow_usd
                        ELSE (0)::numeric
                    END) / (7)::numeric) / NULLIF((sum(
                    CASE
                        WHEN (bridge_flows.date >= (CURRENT_DATE - '30 days'::interval)) THEN bridge_flows.net_flow_usd
                        ELSE (0)::numeric
                    END) / (30)::numeric), (0)::numeric))
                    ELSE NULL::numeric
                END AS velocity_ratio
           FROM public.bridge_flows
          WHERE (bridge_flows.date >= (CURRENT_DATE - '30 days'::interval))
          GROUP BY bridge_flows.chain
        )
 SELECT chain,
    flow_24h,
    flow_7d,
    flow_30d,
    velocity_ratio,
    rank() OVER (ORDER BY flow_7d DESC) AS flow_rank_7d,
        CASE
            WHEN (flow_7d > (50000000)::numeric) THEN 'HOT'::text
            WHEN (flow_7d > (10000000)::numeric) THEN 'WARMING'::text
            WHEN (flow_7d < ('-10000000'::integer)::numeric) THEN 'COOLING'::text
            WHEN (flow_7d < ('-50000000'::integer)::numeric) THEN 'COLD'::text
            ELSE 'NEUTRAL'::text
        END AS rotation_status
   FROM flow_metrics
  ORDER BY flow_7d DESC;


ALTER VIEW public.l2_rotation_rankings OWNER TO postgres;

--
-- Name: VIEW l2_rotation_rankings; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON VIEW public.l2_rotation_rankings IS 'Use this view to identify which L2s are gaining/losing capital';


--
-- Name: learning_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_metrics (
    "timestamp" timestamp without time zone NOT NULL,
    sharpe_ratio double precision,
    win_rate double precision,
    avg_profit double precision,
    exploration_rate double precision,
    strategy_fitness double precision
);


ALTER TABLE public.learning_metrics OWNER TO postgres;

--
-- Name: liquidations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.liquidations (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    side character varying(10) NOT NULL,
    liquidation_value numeric(20,8) NOT NULL,
    price numeric(20,8),
    quantity numeric(20,8),
    "timestamp" timestamp with time zone NOT NULL,
    source character varying(50) DEFAULT 'binance'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.liquidations OWNER TO postgres;

--
-- Name: liquidations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.liquidations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.liquidations_id_seq OWNER TO postgres;

--
-- Name: liquidations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.liquidations_id_seq OWNED BY public.liquidations.id;


--
-- Name: market_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.market_metrics (
    id integer NOT NULL,
    btc_dominance numeric(6,4),
    total_market_cap numeric(20,2),
    total_volume_24h numeric(20,2),
    altcoin_market_cap numeric(20,2),
    defi_dominance numeric(6,4),
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.market_metrics OWNER TO postgres;

--
-- Name: market_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.market_metrics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.market_metrics_id_seq OWNER TO postgres;

--
-- Name: market_metrics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.market_metrics_id_seq OWNED BY public.market_metrics.id;


--
-- Name: market_regimes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.market_regimes (
    id integer NOT NULL,
    regime character varying(50),
    confidence integer,
    btc_dominance double precision,
    trend_direction character varying(20),
    trend_strength double precision,
    volatility double precision,
    fear_greed integer,
    funding_sentiment character varying(50),
    recommended_strategy character varying(50),
    characteristics text[],
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.market_regimes OWNER TO postgres;

--
-- Name: market_regimes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.market_regimes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.market_regimes_id_seq OWNER TO postgres;

--
-- Name: market_regimes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.market_regimes_id_seq OWNED BY public.market_regimes.id;


--
-- Name: model_performance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.model_performance (
    id integer NOT NULL,
    model_name character varying(50) NOT NULL,
    token character varying(20),
    decision_action character varying(10),
    confidence numeric(5,4),
    position_size numeric(12,2),
    scenario character varying(50),
    "timestamp" timestamp with time zone,
    outcome jsonb,
    pnl numeric(12,2),
    profitable boolean,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.model_performance OWNER TO postgres;

--
-- Name: model_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.model_performance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.model_performance_id_seq OWNER TO postgres;

--
-- Name: model_performance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.model_performance_id_seq OWNED BY public.model_performance.id;


--
-- Name: news_articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news_articles (
    id integer NOT NULL,
    title text NOT NULL,
    content text,
    url text NOT NULL,
    source character varying(100),
    published_at timestamp with time zone,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.news_articles OWNER TO postgres;

--
-- Name: news_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.news_articles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.news_articles_id_seq OWNER TO postgres;

--
-- Name: news_articles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.news_articles_id_seq OWNED BY public.news_articles.id;


--
-- Name: open_interest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.open_interest (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    open_interest_contracts numeric(30,8) NOT NULL,
    open_interest_usd numeric(30,2) NOT NULL,
    mark_price numeric(20,8),
    "timestamp" timestamp with time zone NOT NULL,
    source character varying(50) DEFAULT 'binance'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.open_interest OWNER TO postgres;

--
-- Name: open_interest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.open_interest_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.open_interest_id_seq OWNER TO postgres;

--
-- Name: open_interest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.open_interest_id_seq OWNED BY public.open_interest.id;


--
-- Name: options_volatility; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.options_volatility (
    id integer NOT NULL,
    btc_iv numeric(10,2),
    btc_dvol numeric(10,2),
    btc_skew numeric(10,2),
    btc_iv_rank numeric(5,2),
    eth_iv numeric(10,2),
    eth_dvol numeric(10,2),
    eth_skew numeric(10,2),
    eth_iv_rank numeric(5,2),
    avg_iv numeric(10,2),
    volatility_regime character varying(20),
    directional_bias character varying(20),
    risk_level character varying(20),
    position_adjustment numeric(5,3),
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT risk_level_check CHECK (((risk_level)::text = ANY ((ARRAY['HIGH'::character varying, 'MODERATE'::character varying, 'LOW'::character varying, 'NORMAL'::character varying])::text[]))),
    CONSTRAINT vol_regime_check CHECK (((volatility_regime)::text = ANY ((ARRAY['EXTREME'::character varying, 'HIGH'::character varying, 'MODERATE'::character varying, 'LOW'::character varying])::text[])))
);


ALTER TABLE public.options_volatility OWNER TO postgres;

--
-- Name: options_volatility_alerts; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.options_volatility_alerts AS
 SELECT avg_iv,
    volatility_regime,
    directional_bias,
    risk_level,
    position_adjustment,
        CASE
            WHEN (avg_iv > (80)::numeric) THEN 'EXTREME: IV above 80, reduce all positions'::text
            WHEN (avg_iv > (65)::numeric) THEN 'HIGH: Elevated volatility, reduce position sizes'::text
            WHEN ((btc_skew < ('-8'::integer)::numeric) OR (eth_skew < ('-8'::integer)::numeric)) THEN 'SKEW: Heavy put buying detected'::text
            WHEN ((risk_level)::text = 'HIGH'::text) THEN 'RISK: High volatility risk conditions'::text
            ELSE NULL::text
        END AS alert_message,
    scraped_at
   FROM public.options_volatility
  WHERE ((scraped_at > (now() - '01:00:00'::interval)) AND (((risk_level)::text = ANY ((ARRAY['HIGH'::character varying, 'MODERATE'::character varying])::text[])) OR (avg_iv > (65)::numeric) OR (btc_skew < ('-8'::integer)::numeric) OR (eth_skew < ('-8'::integer)::numeric)))
  ORDER BY scraped_at DESC;


ALTER VIEW public.options_volatility_alerts OWNER TO postgres;

--
-- Name: options_volatility_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.options_volatility_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.options_volatility_id_seq OWNER TO postgres;

--
-- Name: options_volatility_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.options_volatility_id_seq OWNED BY public.options_volatility.id;


--
-- Name: options_volatility_latest; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.options_volatility_latest AS
 SELECT btc_iv,
    btc_skew,
    btc_iv_rank,
    eth_iv,
    eth_skew,
    eth_iv_rank,
    avg_iv,
    volatility_regime,
    directional_bias,
    risk_level,
    position_adjustment,
    scraped_at
   FROM public.options_volatility
  ORDER BY scraped_at DESC
 LIMIT 1;


ALTER VIEW public.options_volatility_latest OWNER TO postgres;

--
-- Name: order_book_depth; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_book_depth (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    best_bid numeric(20,8) NOT NULL,
    best_ask numeric(20,8) NOT NULL,
    bid_ask_spread numeric(20,8) NOT NULL,
    bid_liquidity_1pct numeric(30,8),
    ask_liquidity_1pct numeric(30,8),
    order_imbalance numeric(6,4),
    total_bid_volume numeric(30,8),
    total_ask_volume numeric(30,8),
    source character varying(50) DEFAULT 'binance'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.order_book_depth OWNER TO postgres;

--
-- Name: order_book_depth_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.order_book_depth_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.order_book_depth_id_seq OWNER TO postgres;

--
-- Name: order_book_depth_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.order_book_depth_id_seq OWNED BY public.order_book_depth.id;


--
-- Name: paper_trades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paper_trades (
    id integer NOT NULL,
    decision_id integer,
    token character varying(20) NOT NULL,
    side character varying(10) NOT NULL,
    quantity numeric(20,8) NOT NULL,
    price numeric(20,8) NOT NULL,
    value_usd numeric(12,2) NOT NULL,
    fee_pct numeric(5,4) DEFAULT 0.001,
    fee_usd numeric(12,2),
    executed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    trade_pair_id integer,
    is_entry boolean,
    pnl_usd numeric(12,2),
    pnl_pct numeric(8,4),
    slippage_pct numeric(5,4),
    spread_pct numeric(5,4)
);


ALTER TABLE public.paper_trades OWNER TO postgres;

--
-- Name: paper_trades_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.paper_trades_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.paper_trades_id_seq OWNER TO postgres;

--
-- Name: paper_trades_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.paper_trades_id_seq OWNED BY public.paper_trades.id;


--
-- Name: pattern_memory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pattern_memory (
    pattern_hash character varying(64) NOT NULL,
    pattern_features jsonb,
    occurrences integer DEFAULT 1,
    success_rate double precision,
    avg_profit double precision,
    last_seen timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.pattern_memory OWNER TO postgres;

--
-- Name: portfolio_state; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portfolio_state (
    id integer NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    total_value numeric(12,2) NOT NULL,
    cash numeric(12,2) NOT NULL,
    positions_value numeric(12,2) DEFAULT 0,
    positions jsonb DEFAULT '{}'::jsonb,
    daily_pnl numeric(12,2) DEFAULT 0,
    total_pnl numeric(12,2) DEFAULT 0,
    total_pnl_pct numeric(8,4) DEFAULT 0,
    max_drawdown numeric(8,4) DEFAULT 0,
    current_drawdown numeric(8,4) DEFAULT 0,
    total_trades integer DEFAULT 0,
    winning_trades integer DEFAULT 0,
    losing_trades integer DEFAULT 0,
    win_rate numeric(5,4) DEFAULT 0,
    trading_halted boolean DEFAULT false,
    halt_reason text
);


ALTER TABLE public.portfolio_state OWNER TO postgres;

--
-- Name: portfolio_state_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.portfolio_state_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.portfolio_state_id_seq OWNER TO postgres;

--
-- Name: portfolio_state_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.portfolio_state_id_seq OWNED BY public.portfolio_state.id;


--
-- Name: recent_volume_spikes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.recent_volume_spikes AS
 SELECT token,
    (date_trunc('minute'::text, scraped_at) - ((((EXTRACT(minute FROM scraped_at))::integer % 5))::double precision * '00:01:00'::interval)) AS interval_5min,
    count(*) AS tweet_count,
    max(volume_spike) AS max_spike,
    avg(sentiment_score) AS avg_sentiment,
    avg(
        CASE
            WHEN (bot_probability < 0.5) THEN sentiment_score
            ELSE NULL::numeric
        END) AS human_sentiment,
    count(*) FILTER (WHERE (bot_probability >= 0.7)) AS bot_count,
    count(*) FILTER (WHERE (is_whale = true)) AS whale_count
   FROM public.twitter_sentiment
  WHERE (scraped_at > (now() - '01:00:00'::interval))
  GROUP BY token, (date_trunc('minute'::text, scraped_at) - ((((EXTRACT(minute FROM scraped_at))::integer % 5))::double precision * '00:01:00'::interval))
 HAVING (count(*) > 5)
  ORDER BY (max(volume_spike)) DESC NULLS LAST, (date_trunc('minute'::text, scraped_at) - ((((EXTRACT(minute FROM scraped_at))::integer % 5))::double precision * '00:01:00'::interval)) DESC;


ALTER VIEW public.recent_volume_spikes OWNER TO postgres;

--
-- Name: scraper_heartbeats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scraper_heartbeats (
    scraper_name character varying(100) NOT NULL,
    last_run timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.scraper_heartbeats OWNER TO postgres;

--
-- Name: sec_filings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sec_filings (
    id integer NOT NULL,
    cik character varying(20) NOT NULL,
    company_name character varying(255),
    form_type character varying(20) NOT NULL,
    filing_date timestamp with time zone,
    filing_url text NOT NULL,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.sec_filings OWNER TO postgres;

--
-- Name: sec_filings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.sec_filings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sec_filings_id_seq OWNER TO postgres;

--
-- Name: sec_filings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.sec_filings_id_seq OWNED BY public.sec_filings.id;


--
-- Name: stablecoin_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stablecoin_metrics (
    id integer NOT NULL,
    symbol character varying(10) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    market_cap numeric(20,2),
    total_volume_24h numeric(20,2),
    circulating_supply numeric(20,2),
    velocity_ratio numeric(10,4),
    supply_change_24h numeric(20,2),
    supply_change_pct_24h numeric(10,4),
    price_usd numeric(10,6),
    price_deviation_pct numeric(10,4),
    btc_price numeric(20,2),
    total_stablecoin_mcap numeric(20,2),
    dominance_pct numeric(10,4),
    source character varying(50) DEFAULT 'coingecko'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.stablecoin_metrics OWNER TO postgres;

--
-- Name: stablecoin_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.stablecoin_metrics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.stablecoin_metrics_id_seq OWNER TO postgres;

--
-- Name: stablecoin_metrics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.stablecoin_metrics_id_seq OWNED BY public.stablecoin_metrics.id;


--
-- Name: strategy_evolution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.strategy_evolution (
    generation integer NOT NULL,
    parameters jsonb,
    performance jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    parent_generation integer
);


ALTER TABLE public.strategy_evolution OWNER TO postgres;

--
-- Name: tactical_alerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tactical_alerts (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    alert_type character varying(50) NOT NULL,
    urgency character varying(20) NOT NULL,
    confidence integer,
    signals jsonb,
    recommendation character varying(50),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    consumed_at timestamp with time zone
);


ALTER TABLE public.tactical_alerts OWNER TO postgres;

--
-- Name: tactical_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tactical_alerts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tactical_alerts_id_seq OWNER TO postgres;

--
-- Name: tactical_alerts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tactical_alerts_id_seq OWNED BY public.tactical_alerts.id;


--
-- Name: trade_experiences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trade_experiences (
    id integer NOT NULL,
    token character varying(20),
    entry_context jsonb,
    decision jsonb,
    outcome jsonb,
    reward double precision,
    self_reward double precision,
    pattern_hash character varying(64),
    strategy_version integer,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.trade_experiences OWNER TO postgres;

--
-- Name: trade_experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trade_experiences_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.trade_experiences_id_seq OWNER TO postgres;

--
-- Name: trade_experiences_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trade_experiences_id_seq OWNED BY public.trade_experiences.id;


--
-- Name: trading_decisions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trading_decisions (
    id integer NOT NULL,
    token character varying(20) NOT NULL,
    decision_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    tier1_action character varying(10),
    tier1_confidence numeric(5,4),
    tier1_reasoning text,
    tier2_triggered boolean DEFAULT false,
    tier2_action character varying(10),
    tier2_confidence numeric(5,4),
    tier2_consensus_score numeric(5,4),
    final_action character varying(10) NOT NULL,
    final_confidence numeric(5,4),
    position_size_pct numeric(5,2),
    position_size_usd numeric(12,2),
    entry_price numeric(20,8),
    stop_loss numeric(20,8),
    take_profit numeric(20,8),
    sentiment_summary jsonb,
    price_context jsonb,
    status character varying(20) DEFAULT 'PENDING'::character varying,
    executed_at timestamp with time zone,
    rejected_reason text,
    outcome character varying(20),
    exit_price numeric(20,8),
    pnl_usd numeric(12,2),
    pnl_pct numeric(8,4),
    closed_at timestamp with time zone
);


ALTER TABLE public.trading_decisions OWNER TO postgres;

--
-- Name: trading_decisions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trading_decisions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.trading_decisions_id_seq OWNER TO postgres;

--
-- Name: trading_decisions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trading_decisions_id_seq OWNED BY public.trading_decisions.id;


--
-- Name: twitter_sentiment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.twitter_sentiment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.twitter_sentiment_id_seq OWNER TO postgres;

--
-- Name: twitter_sentiment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.twitter_sentiment_id_seq OWNED BY public.twitter_sentiment.id;


--
-- Name: twitter_trading_signals; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.twitter_trading_signals AS
 SELECT token,
    max(volume_spike) AS volume_signal,
    avg(
        CASE
            WHEN (bot_probability < 0.3) THEN sentiment_score
            ELSE NULL::numeric
        END) AS quality_sentiment,
    count(*) FILTER (WHERE ((alert_level)::text = ANY ((ARRAY['HIGH'::character varying, 'EXTREME'::character varying, 'WHALE_SIGNAL'::character varying])::text[]))) AS high_impact_tweets,
    max(
        CASE
            WHEN (pump_score IS NOT NULL) THEN pump_score
            ELSE NULL::numeric
        END) AS pump_risk,
        CASE
            WHEN ((max(volume_spike) >= 3.0) AND (avg(
            CASE
                WHEN (bot_probability < 0.3) THEN sentiment_score
                ELSE NULL::numeric
            END) > 0.2)) THEN 'STRONG BUY'::text
            WHEN ((max(volume_spike) >= 2.0) AND (avg(
            CASE
                WHEN (bot_probability < 0.3) THEN sentiment_score
                ELSE NULL::numeric
            END) > 0.1)) THEN 'BUY'::text
            WHEN ((max(volume_spike) >= 2.0) AND (avg(
            CASE
                WHEN (bot_probability < 0.3) THEN sentiment_score
                ELSE NULL::numeric
            END) < '-0.2'::numeric)) THEN 'SELL'::text
            WHEN (max(pump_score) >= 0.7) THEN 'PUMP WARNING'::text
            ELSE 'HOLD'::text
        END AS signal,
    count(*) AS total_tweets,
    now() AS signal_time
   FROM public.twitter_sentiment
  WHERE (scraped_at > (now() - '00:15:00'::interval))
  GROUP BY token
 HAVING (count(*) >= 5);


ALTER VIEW public.twitter_trading_signals OWNER TO postgres;

--
-- Name: bridge_flow_signals id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_flow_signals ALTER COLUMN id SET DEFAULT nextval('public.bridge_flow_signals_id_seq'::regclass);


--
-- Name: bridge_flows id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_flows ALTER COLUMN id SET DEFAULT nextval('public.bridge_flows_id_seq'::regclass);


--
-- Name: circuit_breaker_events id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.circuit_breaker_events ALTER COLUMN id SET DEFAULT nextval('public.circuit_breaker_events_id_seq'::regclass);


--
-- Name: company_profiles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_profiles ALTER COLUMN id SET DEFAULT nextval('public.company_profiles_id_seq'::regclass);


--
-- Name: congressional_trades id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.congressional_trades ALTER COLUMN id SET DEFAULT nextval('public.congressional_trades_id_seq'::regclass);


--
-- Name: crypto_ohlcv id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crypto_ohlcv ALTER COLUMN id SET DEFAULT nextval('public.crypto_ohlcv_id_seq'::regclass);


--
-- Name: defi_flow_signals id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defi_flow_signals ALTER COLUMN id SET DEFAULT nextval('public.defi_flow_signals_id_seq'::regclass);


--
-- Name: defi_protocols id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defi_protocols ALTER COLUMN id SET DEFAULT nextval('public.defi_protocols_id_seq'::regclass);


--
-- Name: defi_tvl_chains id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defi_tvl_chains ALTER COLUMN id SET DEFAULT nextval('public.defi_tvl_chains_id_seq'::regclass);


--
-- Name: dex_liquidity id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dex_liquidity ALTER COLUMN id SET DEFAULT nextval('public.dex_liquidity_id_seq'::regclass);


--
-- Name: economic_indicators id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.economic_indicators ALTER COLUMN id SET DEFAULT nextval('public.economic_indicators_id_seq'::regclass);


--
-- Name: ensemble_votes id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ensemble_votes ALTER COLUMN id SET DEFAULT nextval('public.ensemble_votes_id_seq'::regclass);


--
-- Name: exchange_flows id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exchange_flows ALTER COLUMN id SET DEFAULT nextval('public.exchange_flows_id_seq'::regclass);


--
-- Name: fear_greed_index id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fear_greed_index ALTER COLUMN id SET DEFAULT nextval('public.fear_greed_index_id_seq'::regclass);


--
-- Name: funding_rates id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_rates ALTER COLUMN id SET DEFAULT nextval('public.funding_rates_id_seq'::regclass);


--
-- Name: liquidations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.liquidations ALTER COLUMN id SET DEFAULT nextval('public.liquidations_id_seq'::regclass);


--
-- Name: market_metrics id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.market_metrics ALTER COLUMN id SET DEFAULT nextval('public.market_metrics_id_seq'::regclass);


--
-- Name: market_regimes id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.market_regimes ALTER COLUMN id SET DEFAULT nextval('public.market_regimes_id_seq'::regclass);


--
-- Name: model_performance id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_performance ALTER COLUMN id SET DEFAULT nextval('public.model_performance_id_seq'::regclass);


--
-- Name: news_articles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_articles ALTER COLUMN id SET DEFAULT nextval('public.news_articles_id_seq'::regclass);


--
-- Name: open_interest id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.open_interest ALTER COLUMN id SET DEFAULT nextval('public.open_interest_id_seq'::regclass);


--
-- Name: options_volatility id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.options_volatility ALTER COLUMN id SET DEFAULT nextval('public.options_volatility_id_seq'::regclass);


--
-- Name: order_book_depth id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_book_depth ALTER COLUMN id SET DEFAULT nextval('public.order_book_depth_id_seq'::regclass);


--
-- Name: paper_trades id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paper_trades ALTER COLUMN id SET DEFAULT nextval('public.paper_trades_id_seq'::regclass);


--
-- Name: portfolio_state id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio_state ALTER COLUMN id SET DEFAULT nextval('public.portfolio_state_id_seq'::regclass);


--
-- Name: sec_filings id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sec_filings ALTER COLUMN id SET DEFAULT nextval('public.sec_filings_id_seq'::regclass);


--
-- Name: stablecoin_metrics id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stablecoin_metrics ALTER COLUMN id SET DEFAULT nextval('public.stablecoin_metrics_id_seq'::regclass);


--
-- Name: tactical_alerts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tactical_alerts ALTER COLUMN id SET DEFAULT nextval('public.tactical_alerts_id_seq'::regclass);


--
-- Name: trade_experiences id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_experiences ALTER COLUMN id SET DEFAULT nextval('public.trade_experiences_id_seq'::regclass);


--
-- Name: trading_decisions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trading_decisions ALTER COLUMN id SET DEFAULT nextval('public.trading_decisions_id_seq'::regclass);


--
-- Name: twitter_sentiment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.twitter_sentiment ALTER COLUMN id SET DEFAULT nextval('public.twitter_sentiment_id_seq'::regclass);


--
-- Name: bridge_flow_signals bridge_flow_signals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_flow_signals
    ADD CONSTRAINT bridge_flow_signals_pkey PRIMARY KEY (id);


--
-- Name: bridge_flows bridge_flows_chain_date_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_flows
    ADD CONSTRAINT bridge_flows_chain_date_key UNIQUE (chain, date);


--
-- Name: bridge_flows bridge_flows_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_flows
    ADD CONSTRAINT bridge_flows_pkey PRIMARY KEY (id);


--
-- Name: circuit_breaker_events circuit_breaker_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.circuit_breaker_events
    ADD CONSTRAINT circuit_breaker_events_pkey PRIMARY KEY (id);


--
-- Name: company_profiles company_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_profiles
    ADD CONSTRAINT company_profiles_pkey PRIMARY KEY (id);


--
-- Name: company_profiles company_profiles_symbol_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_profiles
    ADD CONSTRAINT company_profiles_symbol_key UNIQUE (symbol);


--
-- Name: congressional_trades congressional_trades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.congressional_trades
    ADD CONSTRAINT congressional_trades_pkey PRIMARY KEY (id);


--
-- Name: crypto_ohlcv crypto_ohlcv_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crypto_ohlcv
    ADD CONSTRAINT crypto_ohlcv_pkey PRIMARY KEY (id);


--
-- Name: defi_flow_signals defi_flow_signals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defi_flow_signals
    ADD CONSTRAINT defi_flow_signals_pkey PRIMARY KEY (id);


--
-- Name: defi_protocols defi_protocols_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defi_protocols
    ADD CONSTRAINT defi_protocols_pkey PRIMARY KEY (id);


--
-- Name: defi_tvl_chains defi_tvl_chains_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defi_tvl_chains
    ADD CONSTRAINT defi_tvl_chains_pkey PRIMARY KEY (id);


--
-- Name: dex_liquidity dex_liquidity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dex_liquidity
    ADD CONSTRAINT dex_liquidity_pkey PRIMARY KEY (id);


--
-- Name: economic_indicators economic_indicators_indicator_code_date_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.economic_indicators
    ADD CONSTRAINT economic_indicators_indicator_code_date_key UNIQUE (indicator_code, date);


--
-- Name: economic_indicators economic_indicators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.economic_indicators
    ADD CONSTRAINT economic_indicators_pkey PRIMARY KEY (id);


--
-- Name: ensemble_votes ensemble_votes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ensemble_votes
    ADD CONSTRAINT ensemble_votes_pkey PRIMARY KEY (id);


--
-- Name: exchange_flows exchange_flows_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exchange_flows
    ADD CONSTRAINT exchange_flows_pkey PRIMARY KEY (id);


--
-- Name: fear_greed_index fear_greed_index_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fear_greed_index
    ADD CONSTRAINT fear_greed_index_pkey PRIMARY KEY (id);


--
-- Name: funding_rates funding_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_rates
    ADD CONSTRAINT funding_rates_pkey PRIMARY KEY (id);


--
-- Name: learning_metrics learning_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_metrics
    ADD CONSTRAINT learning_metrics_pkey PRIMARY KEY ("timestamp");


--
-- Name: liquidations liquidations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.liquidations
    ADD CONSTRAINT liquidations_pkey PRIMARY KEY (id);


--
-- Name: market_metrics market_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.market_metrics
    ADD CONSTRAINT market_metrics_pkey PRIMARY KEY (id);


--
-- Name: market_regimes market_regimes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.market_regimes
    ADD CONSTRAINT market_regimes_pkey PRIMARY KEY (id);


--
-- Name: model_performance model_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_performance
    ADD CONSTRAINT model_performance_pkey PRIMARY KEY (id);


--
-- Name: news_articles news_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_articles
    ADD CONSTRAINT news_articles_pkey PRIMARY KEY (id);


--
-- Name: news_articles news_articles_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_articles
    ADD CONSTRAINT news_articles_url_key UNIQUE (url);


--
-- Name: open_interest open_interest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.open_interest
    ADD CONSTRAINT open_interest_pkey PRIMARY KEY (id);


--
-- Name: options_volatility options_volatility_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.options_volatility
    ADD CONSTRAINT options_volatility_pkey PRIMARY KEY (id);


--
-- Name: order_book_depth order_book_depth_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_book_depth
    ADD CONSTRAINT order_book_depth_pkey PRIMARY KEY (id);


--
-- Name: paper_trades paper_trades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paper_trades
    ADD CONSTRAINT paper_trades_pkey PRIMARY KEY (id);


--
-- Name: pattern_memory pattern_memory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pattern_memory
    ADD CONSTRAINT pattern_memory_pkey PRIMARY KEY (pattern_hash);


--
-- Name: portfolio_state portfolio_state_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio_state
    ADD CONSTRAINT portfolio_state_pkey PRIMARY KEY (id);


--
-- Name: scraper_heartbeats scraper_heartbeats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scraper_heartbeats
    ADD CONSTRAINT scraper_heartbeats_pkey PRIMARY KEY (scraper_name);


--
-- Name: sec_filings sec_filings_filing_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sec_filings
    ADD CONSTRAINT sec_filings_filing_url_key UNIQUE (filing_url);


--
-- Name: sec_filings sec_filings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sec_filings
    ADD CONSTRAINT sec_filings_pkey PRIMARY KEY (id);


--
-- Name: stablecoin_metrics stablecoin_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stablecoin_metrics
    ADD CONSTRAINT stablecoin_metrics_pkey PRIMARY KEY (id);


--
-- Name: strategy_evolution strategy_evolution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.strategy_evolution
    ADD CONSTRAINT strategy_evolution_pkey PRIMARY KEY (generation);


--
-- Name: tactical_alerts tactical_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tactical_alerts
    ADD CONSTRAINT tactical_alerts_pkey PRIMARY KEY (id);


--
-- Name: trade_experiences trade_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_experiences
    ADD CONSTRAINT trade_experiences_pkey PRIMARY KEY (id);


--
-- Name: trading_decisions trading_decisions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trading_decisions
    ADD CONSTRAINT trading_decisions_pkey PRIMARY KEY (id);


--
-- Name: twitter_sentiment twitter_sentiment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.twitter_sentiment
    ADD CONSTRAINT twitter_sentiment_pkey PRIMARY KEY (id);


--
-- Name: dex_liquidity unique_dex_reading; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dex_liquidity
    ADD CONSTRAINT unique_dex_reading UNIQUE (token, dex_name, "timestamp");


--
-- Name: fear_greed_index unique_fear_greed; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fear_greed_index
    ADD CONSTRAINT unique_fear_greed UNIQUE ("timestamp");


--
-- Name: funding_rates unique_funding; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funding_rates
    ADD CONSTRAINT unique_funding UNIQUE (token, scraped_at);


--
-- Name: crypto_ohlcv unique_ohlcv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crypto_ohlcv
    ADD CONSTRAINT unique_ohlcv UNIQUE (token, timeframe, "timestamp", source);


--
-- Name: stablecoin_metrics unique_stablecoin_reading; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stablecoin_metrics
    ADD CONSTRAINT unique_stablecoin_reading UNIQUE (symbol, "timestamp");


--
-- Name: congressional_trades unique_transaction; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.congressional_trades
    ADD CONSTRAINT unique_transaction UNIQUE (filer_name, transaction_date, ticker, transaction_type, amount_range);


--
-- Name: twitter_sentiment unique_tweet_token; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.twitter_sentiment
    ADD CONSTRAINT unique_tweet_token UNIQUE (tweet_id, token);


--
-- Name: idx_alert_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alert_level ON public.twitter_sentiment USING btree (alert_level);


--
-- Name: idx_bot_probability; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bot_probability ON public.twitter_sentiment USING btree (bot_probability);


--
-- Name: idx_breaker_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_breaker_time ON public.circuit_breaker_events USING btree (triggered_at DESC);


--
-- Name: idx_bridge_flows_chain; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_flows_chain ON public.bridge_flows USING btree (chain);


--
-- Name: idx_bridge_flows_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_flows_date ON public.bridge_flows USING btree (date DESC);


--
-- Name: idx_bridge_flows_net_flow; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_flows_net_flow ON public.bridge_flows USING btree (net_flow_usd);


--
-- Name: idx_bridge_flows_scraped_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_flows_scraped_at ON public.bridge_flows USING btree (scraped_at DESC);


--
-- Name: idx_bridge_signals_alert; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_signals_alert ON public.bridge_flow_signals USING btree (alert_level);


--
-- Name: idx_bridge_signals_chain; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_signals_chain ON public.bridge_flow_signals USING btree (chain);


--
-- Name: idx_bridge_signals_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_signals_created ON public.bridge_flow_signals USING btree (created_at DESC);


--
-- Name: idx_bridge_signals_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_bridge_signals_type ON public.bridge_flow_signals USING btree (signal_type);


--
-- Name: idx_decisions_outcome; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_decisions_outcome ON public.trading_decisions USING btree (outcome);


--
-- Name: idx_decisions_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_decisions_status ON public.trading_decisions USING btree (status);


--
-- Name: idx_decisions_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_decisions_time ON public.trading_decisions USING btree (decision_time DESC);


--
-- Name: idx_decisions_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_decisions_token ON public.trading_decisions USING btree (token);


--
-- Name: idx_defi_chains_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_chains_name ON public.defi_tvl_chains USING btree (chain_name);


--
-- Name: idx_defi_chains_scraped; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_chains_scraped ON public.defi_tvl_chains USING btree (scraped_at DESC);


--
-- Name: idx_defi_chains_tvl; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_chains_tvl ON public.defi_tvl_chains USING btree (tvl_usd DESC);


--
-- Name: idx_defi_protocols_category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_protocols_category ON public.defi_protocols USING btree (category);


--
-- Name: idx_defi_protocols_change_1d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_protocols_change_1d ON public.defi_protocols USING btree (change_1d_pct DESC);


--
-- Name: idx_defi_protocols_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_protocols_name ON public.defi_protocols USING btree (protocol_name);


--
-- Name: idx_defi_protocols_scraped; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_protocols_scraped ON public.defi_protocols USING btree (scraped_at DESC);


--
-- Name: idx_defi_protocols_tvl; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_protocols_tvl ON public.defi_protocols USING btree (tvl_usd DESC);


--
-- Name: idx_defi_signals_risk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_signals_risk ON public.defi_flow_signals USING btree (risk_indicator);


--
-- Name: idx_defi_signals_scraped; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_defi_signals_scraped ON public.defi_flow_signals USING btree (scraped_at DESC);


--
-- Name: idx_dex_liquidity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dex_liquidity ON public.dex_liquidity USING btree (liquidity_usd DESC);


--
-- Name: idx_dex_ratio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dex_ratio ON public.dex_liquidity USING btree (volume_to_liquidity_ratio DESC);


--
-- Name: idx_dex_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dex_timestamp ON public.dex_liquidity USING btree ("timestamp" DESC);


--
-- Name: idx_dex_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dex_token ON public.dex_liquidity USING btree (token);


--
-- Name: idx_dex_volume; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dex_volume ON public.dex_liquidity USING btree (volume_24h DESC);


--
-- Name: idx_fear_greed_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fear_greed_timestamp ON public.fear_greed_index USING btree ("timestamp" DESC);


--
-- Name: idx_fear_greed_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fear_greed_value ON public.fear_greed_index USING btree (value);


--
-- Name: idx_flows_signal; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flows_signal ON public.exchange_flows USING btree (signal_strength DESC);


--
-- Name: idx_flows_smart_money; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flows_smart_money ON public.exchange_flows USING btree (is_smart_money);


--
-- Name: idx_flows_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flows_timestamp ON public.exchange_flows USING btree ("timestamp" DESC);


--
-- Name: idx_flows_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flows_token ON public.exchange_flows USING btree (token);


--
-- Name: idx_flows_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flows_type ON public.exchange_flows USING btree (flow_type);


--
-- Name: idx_flows_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flows_value ON public.exchange_flows USING btree (usd_value DESC);


--
-- Name: idx_funding_rate; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_funding_rate ON public.funding_rates USING btree (funding_rate DESC);


--
-- Name: idx_funding_scraped_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_funding_scraped_at ON public.funding_rates USING btree (scraped_at DESC);


--
-- Name: idx_funding_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_funding_token ON public.funding_rates USING btree (token);


--
-- Name: idx_funding_token_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_funding_token_time ON public.funding_rates USING btree (token, scraped_at DESC);


--
-- Name: idx_hourly_volume_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_hourly_volume_token ON public.hourly_twitter_volume USING btree (token, hour DESC);


--
-- Name: idx_is_whale; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_is_whale ON public.twitter_sentiment USING btree (is_whale);


--
-- Name: idx_liquidations_side; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_liquidations_side ON public.liquidations USING btree (side);


--
-- Name: idx_liquidations_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_liquidations_timestamp ON public.liquidations USING btree ("timestamp" DESC);


--
-- Name: idx_liquidations_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_liquidations_token ON public.liquidations USING btree (token);


--
-- Name: idx_liquidations_token_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_liquidations_token_time ON public.liquidations USING btree (token, "timestamp" DESC);


--
-- Name: idx_liquidations_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_liquidations_value ON public.liquidations USING btree (liquidation_value DESC);


--
-- Name: idx_market_metrics_btc_dom; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_market_metrics_btc_dom ON public.market_metrics USING btree (btc_dominance);


--
-- Name: idx_market_metrics_scraped; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_market_metrics_scraped ON public.market_metrics USING btree (scraped_at DESC);


--
-- Name: idx_model_performance_model; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_model_performance_model ON public.model_performance USING btree (model_name);


--
-- Name: idx_model_performance_scenario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_model_performance_scenario ON public.model_performance USING btree (scenario);


--
-- Name: idx_model_performance_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_model_performance_timestamp ON public.model_performance USING btree ("timestamp" DESC);


--
-- Name: idx_model_performance_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_model_performance_token ON public.model_performance USING btree (token);


--
-- Name: idx_momentum_score; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_momentum_score ON public.twitter_sentiment USING btree (momentum_score DESC);


--
-- Name: idx_news_published_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_news_published_at ON public.news_articles USING btree (published_at DESC);


--
-- Name: idx_news_scraped_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_news_scraped_at ON public.news_articles USING btree (scraped_at DESC);


--
-- Name: idx_news_source; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_news_source ON public.news_articles USING btree (source);


--
-- Name: idx_ohlcv_timeframe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ohlcv_timeframe ON public.crypto_ohlcv USING btree (timeframe);


--
-- Name: idx_ohlcv_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ohlcv_timestamp ON public.crypto_ohlcv USING btree ("timestamp" DESC);


--
-- Name: idx_ohlcv_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ohlcv_token ON public.crypto_ohlcv USING btree (token);


--
-- Name: idx_ohlcv_token_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ohlcv_token_time ON public.crypto_ohlcv USING btree (token, "timestamp" DESC);


--
-- Name: idx_oi_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_oi_timestamp ON public.open_interest USING btree ("timestamp" DESC);


--
-- Name: idx_oi_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_oi_token ON public.open_interest USING btree (token);


--
-- Name: idx_oi_token_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_oi_token_time ON public.open_interest USING btree (token, "timestamp" DESC);


--
-- Name: idx_oi_usd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_oi_usd ON public.open_interest USING btree (open_interest_usd DESC);


--
-- Name: idx_options_vol_avg_iv; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_options_vol_avg_iv ON public.options_volatility USING btree (avg_iv);


--
-- Name: idx_options_vol_btc_iv; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_options_vol_btc_iv ON public.options_volatility USING btree (btc_iv);


--
-- Name: idx_options_vol_eth_iv; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_options_vol_eth_iv ON public.options_volatility USING btree (eth_iv);


--
-- Name: idx_options_vol_risk_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_options_vol_risk_level ON public.options_volatility USING btree (risk_level);


--
-- Name: idx_options_vol_scraped_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_options_vol_scraped_at ON public.options_volatility USING btree (scraped_at DESC);


--
-- Name: idx_orderbook_imbalance; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orderbook_imbalance ON public.order_book_depth USING btree (order_imbalance DESC);


--
-- Name: idx_orderbook_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orderbook_timestamp ON public.order_book_depth USING btree ("timestamp" DESC);


--
-- Name: idx_orderbook_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orderbook_token ON public.order_book_depth USING btree (token);


--
-- Name: idx_orderbook_token_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orderbook_token_time ON public.order_book_depth USING btree (token, "timestamp" DESC);


--
-- Name: idx_portfolio_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_portfolio_time ON public.portfolio_state USING btree ("timestamp" DESC);


--
-- Name: idx_pump_score; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pump_score ON public.twitter_sentiment USING btree (pump_score);


--
-- Name: idx_regime_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_regime_created ON public.market_regimes USING btree (created_at);


--
-- Name: idx_sentiment_velocity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sentiment_velocity ON public.twitter_sentiment USING btree (sentiment_velocity DESC);


--
-- Name: idx_source; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_source ON public.twitter_sentiment USING btree (source);


--
-- Name: idx_stablecoin_supply_change; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_stablecoin_supply_change ON public.stablecoin_metrics USING btree (supply_change_pct_24h DESC);


--
-- Name: idx_stablecoin_symbol; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_stablecoin_symbol ON public.stablecoin_metrics USING btree (symbol);


--
-- Name: idx_stablecoin_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_stablecoin_timestamp ON public.stablecoin_metrics USING btree ("timestamp" DESC);


--
-- Name: idx_stablecoin_velocity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_stablecoin_velocity ON public.stablecoin_metrics USING btree (velocity_ratio DESC);


--
-- Name: idx_tactical_alerts_consumed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tactical_alerts_consumed ON public.tactical_alerts USING btree (consumed_at);


--
-- Name: idx_tactical_alerts_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tactical_alerts_created ON public.tactical_alerts USING btree (created_at DESC);


--
-- Name: idx_tactical_alerts_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tactical_alerts_token ON public.tactical_alerts USING btree (token);


--
-- Name: idx_trades_decision; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trades_decision ON public.paper_trades USING btree (decision_id);


--
-- Name: idx_trades_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trades_time ON public.paper_trades USING btree (executed_at DESC);


--
-- Name: idx_trades_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trades_token ON public.paper_trades USING btree (token);


--
-- Name: idx_twitter_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_twitter_created_at ON public.twitter_sentiment USING btree (tweet_created_at);


--
-- Name: idx_twitter_scraped_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_twitter_scraped_at ON public.twitter_sentiment USING btree (scraped_at);


--
-- Name: idx_twitter_sentiment_score; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_twitter_sentiment_score ON public.twitter_sentiment USING btree (sentiment_score);


--
-- Name: idx_twitter_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_twitter_token ON public.twitter_sentiment USING btree (token);


--
-- Name: idx_verified; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_verified ON public.twitter_sentiment USING btree (verified);


--
-- Name: idx_volume_acceleration; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_volume_acceleration ON public.twitter_sentiment USING btree (volume_acceleration DESC);


--
-- Name: idx_volume_spike; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_volume_spike ON public.twitter_sentiment USING btree (volume_spike DESC);


--
-- Name: idx_votes_decision; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_votes_decision ON public.ensemble_votes USING btree (decision_id);


--
-- Name: idx_votes_model; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_votes_model ON public.ensemble_votes USING btree (model_name);


--
-- Name: idx_weighted_score; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_weighted_score ON public.twitter_sentiment USING btree (weighted_score DESC);


--
-- Name: ensemble_votes ensemble_votes_decision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ensemble_votes
    ADD CONSTRAINT ensemble_votes_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES public.trading_decisions(id);


--
-- Name: paper_trades paper_trades_decision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paper_trades
    ADD CONSTRAINT paper_trades_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES public.trading_decisions(id);


--
-- PostgreSQL database dump complete
--

\unrestrict FCHgTsLP6K3LdVfb7hlNmqkL3NsMTCu1Bgfi4xHr7T4mpP9g6xVEVnpmCjbeG7m

